### ISSUE TITLE
Revert bartender RP to stable version

### ISSUE THREAD

**Issue by jansauer** [caskroom/homebrew-cask#12128] opened 2015-06-26 15:08 UTC
With #11288 bartender was updated to version 1.2.40.
This version is not listed in the appcast and also not on the website.
As of the website and the app updater 1.2.39 ist still the current stable release.

**Comment by vitorgalvao** [comment] 2015-06-26 16:55
Confirmed. Where have you got the version from, @mauricerkelly. Beta tester?

**Comment by mauricerkelly** [comment] 2015-06-26 17:06
Looks like I am, though I was not aware of it:

![screenshot of bartender 26-06-2015 18 04 12](https://cloud.githubusercontent.com/assets/729402/8382868/de9d5e40-1c2d-11e5-84bb-0dfbd1dbadd4.png)

My apologies.

**Comment by vitorgalvao** [comment] 2015-06-26 17:15
Anyone wants to submit a fix?

**Comment by mauricerkelly** [comment] 2015-06-26 17:18
Sure, I’ll do one now. I only just woke up and thought this was a PR already :-)

**Comment by fanquake** [comment] 2015-07-02 18:36
Fixed in #12129

**Closed by fanquake** 2015-07-02 18:36 UTC
