### ISSUE TITLE
install inkscape checksum failed

### ISSUE THREAD

**Issue by julienlavergne** [caskroom/homebrew-cask#14550] opened 2015-10-20 19:39 UTC
Hello,

When I want to install inkscape, I get this issue:

however I get this issue:

Error: Execution of 'brew cask install inkscape' returned 1: Error: sha256 mismatch
Expected: 66c9af880f87d5b64006391fc8dd2d3f546d93d6d91235eba7856deacba29862
Actual: a9f6ec70d9fcd16ee2e5ac3539d0ba6daefc6a87923f1dc3c2dfb45b22d4720b
File: /Library/Caches/Homebrew/inkscape-0.91-1.dmg
To retry an incomplete download, remove the file above.
==> Satisfying dependencies
complete
==> Downloading https://inkscape.global.ssl.fastly.net/media/resources/file/Inkscape-0.91-1-x11-10.7-x86_64.dmg
Already downloaded: /Library/Caches/Homebrew/inkscape-0.91-1.dmg
==> Note: running "brew update" may fix sha256 checksum errors
Error: /Stage[main]/Main/Package[inkscape]/ensure: change from absent to present failed: Execution of 'brew cask install inkscape' returned 1: Error: sha256 mismatch
Expected: 66c9af880f87d5b64006391fc8dd2d3f546d93d6d91235eba7856deacba29862
Actual: a9f6ec70d9fcd16ee2e5ac3539d0ba6daefc6a87923f1dc3c2dfb45b22d4720b
File: /Library/Caches/Homebrew/inkscape-0.91-1.dmg
To retry an incomplete download, remove the file above.
==> Satisfying dependencies
complete
==> Downloading https://inkscape.global.ssl.fastly.net/media/resources/file/Inkscape-0.91-1-x11-10.7-x86_64.dmg
Already downloaded: /Library/Caches/Homebrew/inkscape-0.91-1.dmg
==> Note: running "brew update" may fix sha256 checksum errors

Any idea ?

**Comment by vitorgalvao** [comment] 2015-10-20 19:41
```ruby
File: /Library/Caches/Homebrew/inkscape-0.91-1.dmg
To retry an incomplete download, remove the file above.
```

Have you done so? Also, [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by vitorgalvao** [comment] 2015-10-22 16:00
Closing due to no reply even though user already interacted with the issue after question. In addition, problem is likely on user end (could no reproduce, and pointed out likely issue).

**Closed by vitorgalvao** 2015-10-22 16:00 UTC
Labels: awaiting user reply
