### ISSUE TITLE
Package installed but is shown as not installed

### ISSUE THREAD

**Issue by nvdv** [caskroom/homebrew-cask#9363] opened 2015-02-01 06:49 UTC
Hi,
few days ago LibreOffice 4.4.4 came out and now it is shown not installed package, but previous version is definitely installed:
 
```
> brew cask list
basictex     flux	  java	       libreoffice  vagrant	 virtualbox

> brew cask info libreoffice
libreoffice: 4.4.0
libreoffice
https://www.libreoffice.org/
Not installed
https://github.com/caskroom/homebrew-cask/blob/master/Casks/libreoffice.rb
==> Contents
  LibreOffice.app (app)
```

**Comment by lvillani** [comment] 2015-02-01 11:45
In my experience this happens when the cask is bound to a specific version (i.e.: the version qualifier isn't "latest") and the cask itself is updated.

On one hand, it is right. That _specific version_ of the cask is not installed. Anyway, I think it's confusing.

**Comment by lvillani** [comment] 2015-02-01 11:47
Btw, this looks like a duplicate of #2988

**Comment by vitorgalvao** [comment] 2015-02-01 13:34
You are correct.

**Closed by vitorgalvao** 2015-02-01 13:34 UTC
