### ISSUE TITLE
Bug report: Error installing mactex

### ISSUE THREAD

**Issue by wlhlm** [caskroom/homebrew-cask#25395] opened 2016-10-11 15:15 UTC
#### Description of issue

Trying to install mactex fails:

```
$ brew cask install mactex
==> Downloading http://mirror.ctan.org/systems/mac/mactex/mactex-20161009.pkg
Already downloaded: /Users/wlhlm/Library/Caches/Homebrew/Cask/mactex--20161009.pkg
==> Verifying checksum for Cask mactex
==> Running installer for mactex; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Package name is MacTeX-2016
==> installer: Installing at base path /
==> installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the sof
Error: no implicit conversion of Array into String
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/exceptions.rb:71:in `concat'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/exceptions.rb:71:in `to_s'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `message'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:143:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

I'm aware of #7946, but wasn't able to fix the problem by updating hombrew cask.

<details><summary>

Output of `brew cask <command> --verbose`</summary>

```
==> Downloading http://mirror.ctan.org/systems/mac/mactex/mactex-20161009.pkg
Already downloaded: /Users/wlhlm/Library/Caches/Homebrew/Cask/mactex--20161009.pkg
==> Verifying checksum for Cask mactex
==> Running installer for mactex; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is MacTeX-2016
==> installer: Installing at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing MacTeX-2016…
==> installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Error: no implicit conversion of Array into String
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/exceptions.rb:71:in `concat'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/exceptions.rb:71:in `to_s'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `message'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:143:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

</details>

<details><summary>

Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Xcode (7.0) is outdated.
Please update to Xcode 7.2.1 (or delete it).
Xcode can be updated from the App Store.

```

</details>

<details><summary>

Output of `brew cask doctor`</summary>

```
$ brew cask doctor
==> macOS Release:
10.10.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.0.7-9-g04ccba5
Homebrew/homebrew-core (git revision fa7b2; last commit 2016-10-11)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-Cask Version:
Homebrew-Cask 1.0.7-9-g04ccba5
caskroom/homebrew-cask (git revision a3e9; last commit 2016-10-11)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/wlhlm/Library/Caches/Homebrew/Cask
8 files, 2.8G (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions
==> Homebrew-Cask Default Tap Cask Count:
3376
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
==> Running As Privileged User:
No
```

</details>

**Comment by reitermarkus** [comment] 2016-10-11 16:39
Does installing the `pkg` manually work?

**Comment by wlhlm** [comment] 2016-10-12 05:59
Yes, works without a problem.

**Comment by reitermarkus** [comment] 2016-10-13 18:34
It is installing fine for me, I cannot reproduce the error you are getting:

```
The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
```

**Comment by jawshooah** [comment] 2016-10-21 03:47
@wlhlm Try `brew cask uninstall --force mactex && brew cask install mactex`

**Comment by adidalal** [comment] 2016-11-05 18:40
Closing due to lack of reply

**Closed by adidalal** 2016-11-05 18:40 UTC
