### ISSUE TITLE
LibreOffice won't upgrade

### ISSUE THREAD

**Issue by elektronaut0815** [caskroom/homebrew-cask#32830] opened 2017-04-22 14:42 UTC
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Cask seems to have some issue on my machine, one problem is that it won't upgrade LibreOffice. 
Even though version 5.3.2 is reported by cask, 5.1.0.3 remains installed.

#### Output of your command with `--verbose --debug`

```
$ brew cask reinstall libreoffice --verbose --debug
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
complete
==> Downloading
==> Downloading https://download.documentfoundation.org/libreoffice/stable/5.3.2/mac/x86_64/LibreOffice_5.3.2_MacOS_x86-64.dmg
==> Calling curl with args ["https://download.documentfoundation.org/libreoffice/stable/5.3.2/mac/x86_64/LibreOffice_5.3.2_MacOS_x86-64.dmg", "-C", "0", "-o", "#<Pathname:/Users/me/Library/Caches/Homebrew/Cask/libreoffice--5.3.2.dmg.incomplete>"]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.1.13-63-g206d6de845 (Macintosh; Intel macOS 10.12.4) curl/7.51.0 --fail https://download.documentfoundation.org/libreoffice/stable/5.3.2/mac/x86_64/LibreOffice_5.3.2_MacOS_x86-64.dmg -C 0 -o /Users/me/Library/Caches/Homebrew/Cask/libreoffice--5.3.2.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   425    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  216M  100  216M    0     0  12.8M      0  0:00:16  0:00:16 --:--:-- 8711k
==> Downloaded to -> /Users/me/Library/Caches/Homebrew/Cask/libreoffice--5.3.2.dmg
==> Verifying download
==> Determining which verifications to run for Cask libreoffice
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask libreoffice
==> SHA256 checksums match
Warning: Calling MacOS.release is deprecated!
Use MacOS.version instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:10:in `block in load'

==> Hbc::Installer#uninstall
==> Un-installing artifacts
==> Determining which artifacts are present in Cask libreoffice
==> 3 artifact/s defined
#<Hbc::Artifact::App:0x007fc1ab830490>
#<Hbc::Artifact::Binary:0x007fc1ab830378>
#<Hbc::Artifact::Zap:0x007fc1ab830260>
==> Un-installing artifact of class Hbc::Artifact::App
==> Removing App '/Applications/LibreOffice.app'.
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Purging files for version 5.1.0 of Cask libreoffice
==> Purging all staged versions of Cask libreoffice
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/me/Library/Caches/Homebrew/Cask/libreoffice--5.3.2.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/me/Library/Caches/Homebrew/Cask/libreoffice--5.3.2.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "/Users/me/Library/Caches/Homebrew/Cask/libreoffice--5.3.2.dmg"]
==> Purging files for version 5.3.2 of Cask libreoffice
Error: Command failed to execute!

==> Failed command:
/usr/bin/hdiutil mount -plist -nobrowse -readonly -noidme -mountrandom /tmp #<Pathname:/Users/me/Library/Caches/Homebrew/Cask/libreoffice--5.3.2.dmg>

==> Standard Output of failed command:


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 41852 SIGPIPE (signal 13)>
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:65:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:31:in `mount!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:23:in `extract'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:131:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:69:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:30:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.13-63-g206d6de845
caskroom/homebrew-cask (git revision c9fd; last commit 2017-04-22)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 223.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3635 casks)
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree (0 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (160 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-apache (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-x11 (0 casks)
/usr/local/Homebrew/Library/Taps/pivotal/homebrew-tap (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="de_DE.UTF-8"
PATH="~/bin:~/code/libs/play-2.2.1:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/heroku/bin:/Applications/android-sdk/sdk/platform-tools:/Applications/android-sdk/sdk/build-tools/22.0.1:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/Cellar/gradle/2.11/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin:/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```
#### Might be related

Some remains of cloudfoundry-cli won't disappear:
```
$ brew cask outdated --verbose --debug
Error: No available Cask for cloudfoundry-cli/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:111:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:128:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:40:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:30:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:30:in `installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/outdated.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'

$ brew cask uninstall cloudfoundry-cli --verbose --debug
==> Uninstalling Cask cloudfoundry-cli
Error: No available Cask for cloudfoundry-cli/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:111:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:128:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:11:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```
So here I am stuck now, thanks in advance for any advice!

**Comment by commitay** [comment] 2017-04-23 10:35
I can reproduce this.
```
brew cask install libreoffice
==> Satisfying dependencies
complete
==> Downloading https://download.documentfoundation.org/libreoffice/stable/5.3.2
######################################################################## 100.0%
==> Verifying checksum for Cask libreoffice
==> Installing Cask libreoffice
Error: Command failed to execute!

==> Failed command:
/usr/bin/hdiutil mount -plist -nobrowse -readonly -noidme -mountrandom /tmp #<Pathname:/Users/commitay/Library/Caches/Homebrew/Cask/libreoffice--5.3.2.dmg>

==> Standard Output of failed command:


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 2021 SIGPIPE (signal 13)>
Error: nothing to install
```
-----
I was able to fix this by manually ejecting the `LibreOffice` disk using `Disk Utility` and running `brew cask install libreoffice` again.

**Comment by danielmartin** [comment] 2017-04-23 19:55
Same error trying to install `google-chrome`.

**Comment by elektronaut0815** [comment] 2017-04-23 21:14
Trying this again (`brew cask reinstall libreoffice`) somehow got up to the point where at least the old installation got removed. After that, `brew cask install libreoffice` installed the new version. So that problem is solved for me now, although the process seems broken.

The trouble with `cloudfoundry-cli` remains. 

I hesitate to close this issue as it seems as if a reasonable fix is needed.

**Comment by commitay** [comment] 2017-04-23 23:09
I can't reliably reproduce this error. Testing this all I'm doing is rolling back the VM snapshot and doing a clean install of HB/HBC.

```
brew cask install libreoffice
==> Satisfying dependencies
complete
==> Downloading https://download.documentfoundation.org/libreoffice/stable/5.3.2
######################################################################## 100.0%
==> Verifying checksum for Cask libreoffice
==> Moving App 'LibreOffice.app' to '/Applications/LibreOffice.app'.
==> Linking Binary 'gengal' to '/usr/local/bin/gengal'.
==> Linking Binary 'regmerge' to '/usr/local/bin/regmerge'.
==> Linking Binary 'regview' to '/usr/local/bin/regview'.
==> Linking Binary 'senddoc' to '/usr/local/bin/senddoc'.
==> Linking Binary 'ui-previewer' to '/usr/local/bin/ui-previewer'.
==> Linking Binary 'uno' to '/usr/local/bin/uno'.
==> Linking Binary 'unopkg' to '/usr/local/bin/unopkg'.
==> Linking Binary 'urelibs' to '/usr/local/bin/urelibs'.
==> Linking Binary 'uri-encode' to '/usr/local/bin/uri-encode'.
==> Linking Binary 'xpdfimport' to '/usr/local/bin/xpdfimport'.
==> Linking Binary 'soffice.wrapper.sh' to '/usr/local/bin/soffice'.
🍺  libreoffice was successfully installed!
```

```
brew cask install google-chrome
==> Satisfying dependencies
complete
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
######################################################################## 100.0%
==> No checksum defined for Cask google-chrome, skipping verification
==> Installing Cask google-chrome
Error: Command failed to execute!

==> Failed command:
/usr/bin/hdiutil mount -plist -nobrowse -readonly -noidme -mountrandom /tmp #<Pathname:/Users/commitay/Library/Caches/Homebrew/Cask/google-chrome--latest.dmg>

==> Standard Output of failed command:


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 1958 SIGPIPE (signal 13)>
Error: nothing to install
```

```
brew cask install google-chrome
==> Satisfying dependencies
complete
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
######################################################################## 100.0%
==> No checksum defined for Cask google-chrome, skipping verification
==> Moving App 'Google Chrome.app' to '/Applications/Google Chrome.app'.
🍺  google-chrome was successfully installed!
```

**Comment by miccal** [comment] 2017-04-23 23:14
I cannot reproduce this.

**Comment by andershammar** [comment] 2017-04-25 11:04
I'm getting the same error when trying to install Spotify. Un-mounting the disk with `Disk Utility` and retrying does not help for me.

```
$ brew cask install spotify
==> Satisfying dependencies
complete
==> Downloading https://download.spotify.com/Spotify.dmg
######################################################################## 100.0%
==> No checksum defined for Cask spotify, skipping verification
==> Installing Cask spotify
Error: Command failed to execute!

==> Failed command:
/usr/bin/hdiutil mount -plist -nobrowse -readonly -noidme -mountrandom /tmp #<Pathname:/Users/23051884/Library/Caches/Homebrew/Cask/spotify--latest.dmg>

==> Standard Output of failed command:


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 13157 SIGPIPE (signal 13)>
Error: nothing to install
```

**Comment by commitay** [comment] 2017-04-25 11:09
> Un-mounting the disk with Disk Utility and retrying does not help for me.

This will only work with versioned casks. `google-chrome` and `spotify` are both `version :latest`

**Comment by commitay** [comment] 2017-04-25 21:39
@elektronaut0815 , @danielmartin , @andershammar 

Please post the output of `brew config`.

**Comment by elektronaut0815** [comment] 2017-04-26 05:31
Thank you for your attention, here it is:
```
$ brew config
HOMEBREW_VERSION: 1.1.13-63-g206d6de845
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 206d6de845c9041bbbd4d955e56befb338295e96
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ddb97ac4a59967bcbd8542cb673f994bec61951d
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_74, 1.8.0_66, 1.7.0_67
macOS: 10.12.4-x86_64
Xcode: 8.2
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

**Comment by andershammar** [comment] 2017-04-26 08:40
Here's mine.

```
$ brew config
HOMEBREW_VERSION: 1.1.13-3683-g24a339ee
ORIGIN: https://github.com/Homebrew/brew
HEAD: 24a339ee239a4e13e5162085780687fcd2b7bc9f
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0b669484c85ab945cd0d49b920fdb3f0e40d7cbd
Core tap last commit: 33 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_131, 1.6.0_65-b14-468
macOS: 10.12.4-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

Maybe I should also mention that so far I have only seen this problem when trying to install Spotify. Other casks are installing fine.

**Comment by commitay** [comment] 2017-04-26 10:50
@elektronaut0815 , @andershammar Thank you both for supplying `brew config`.

-----

@elektronaut0815 If you have already uninstalled `cloudfoundry-cli`, you can remove the `cloudfoundry-cli` folder from `/usr/local/Caskroom`, that should fix the error with `brew cask outdated`.

-----

@miccal I'm able to consistently reproduce this error with `google-chrome` and `spotify` by switching to `master` from `1.1.13` tag. 

I can also reproduce this with `libreoffice` but only when it is a fresh download/install on `master`, installing with `1.1.13` and reinstalling on `master` does not error. 

I'm guessing this is because it has already accessed the `.dmg` whereas `google-chrome` and `spotify` are `:latest` so HBC always downloads the cask again.

**Comment by andershammar** [comment] 2017-04-26 11:01
@commitay Thanks the update. I was able to install Spotify by following your example, i.e. moving back to the `1.1.13` tag.

**Comment by miccal** [comment] 2017-04-26 11:10
@commitay I cannot reproduce this error at all.

**Comment by elektronaut0815** [comment] 2017-04-26 12:22
@commitay Thank you, deleting the folder fixed that error!

**Comment by danielmartin** [comment] 2017-04-29 12:21
I've done root cause analysis of this problem and the issue seems to be this commit: https://github.com/Homebrew/brew/commit/cc634b2d50cc0e8c1e8a38196f4bcdad4e0a69b6 Incrementing the timeout fixed the issue, at least on my machine. The fact that this problem was not easily reproducible makes now sense because, as with every timing issue, it depends on the machine speed and the size of the cask.

I can prepare a patch if you want if you confirm this fixes the problem for you in Homebrew `master`.

**Comment by commitay** [comment] 2017-04-29 22:36
@danielmartin Thank you for investigating this.

> Incrementing the timeout fixed the issue

This works for me when installing `libreoffice` , `google-chrome` and `spotify`. 

It also seems to resolve https://github.com/caskroom/homebrew-cask/issues/33116.

**Comment by commitay** [comment] 2017-05-06 00:25
@miccal I think this can be closed as https://github.com/Homebrew/brew/issues/2571 has been merged.

**Closed** 2017-05-06 09:05 UTC
