### ISSUE TITLE
Java Cask Error

### ISSUE THREAD

**Issue by henrylawson** [caskroom/homebrew-cask#21530] opened 2016-05-29 09:53 UTC
### Description of issue
Below error when doing a `brew cask install java`

```
$ brew cask install java
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u92-b14/jdk-8u92-macosx-x64.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask java
==> hdiutil: mount failed - Protocol wrong type for socket
Error: Empty plist input
```

Opening the DMG from finder in `/Library/Caches/Homebrew/java-1.8.0_92-b14.dmg` shows a window with the error "Image: java-1.8.0_92-b14.dmg Reason: Protocol wrong type for socket".

### Output of `brew cask <command> --verbose`

```
$ brew cask install java --verbose
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u92-b14/jdk-8u92-macosx-x64.dmg
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-648) http://download.oracle.com/otn-pub/java/jdk/8u92-b14/jdk-8u92-macosx-x64.dmg -C 0 -o /Library/Caches/Homebrew/java-1.8.0_92-b14.dmg.incomplete -b oraclelicense=accept-securebackup-cookie
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   298  100   298    0     0    174      0  0:00:01  0:00:01 --:--:--   523
100   457  100   457    0     0    226      0  0:00:02  0:00:02 --:--:--     0
100  227M  100  227M    0     0  2796k      0  0:01:23  0:01:23 --:--:-- 2554k
==> Verifying checksum for Cask java
==> hdiutil: mount failed - Protocol wrong type for socket
Error: Empty plist input
Error: Kernel.exit
```

### Output of `brew doctor`

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    docker-compose

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
    /Users/hlawson/go/bin/

Warning: Your Xcode (7.3) is outdated
Please update to Xcode 7.3.1.
Xcode can be updated from the App Store.
```

### Output of `brew cask doctor`

```
$ brew cask doctor
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 146a1; last commit 2016-05-29)
Homebrew/homebrew-core (git revision 93b68; last commit 2016-05-29)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-cask Version:
0.60.0 (git revision fc7c5; last commit 5 hours ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
2 files, 454.6M (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
/usr/local/Library/Taps/caskroom/homebrew-fonts
==> Homebrew-cask Default Tap Cask Count:
3180
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/hlawson/.rbenv/bin:/Users/hlawson/.rbenv/shims:/Users/hlawson/Workspace/tunnelblick-script:/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/hlawson/android-sdk-macosx/tools:/Users/hlawson/android-sdk-macosx/platform-tools:/Users/hlawson/.bash/bin:/Users/hlawson/.composer/vendor/bin:/usr/local/opt/go/libexec/bin:/Users/hlawson/go/bin/:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/Taps/homebrew/homebrew-brewdler/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_AU.UTF-8"
==>
```

**Comment by adidalal** [comment] 2016-05-29 14:52
That's normally an error you get with a bad download, try clearing the cache and redownloading?

**Comment by henrylawson** [comment] 2016-05-29 15:07
Have tried that a few times, same result.

**Comment by vitorgalvao** [comment] 2016-06-07 16:17
I cannot reproduce this at all.

> Opening the DMG from finder in `/Library/Caches/Homebrew/java-1.8.0_92-b14.dmg` shows a window with the error "Image: java-1.8.0_92-b14.dmg Reason: Protocol wrong type for socket".

This suggest the issue is entirely on the downloaded file, not on HBC. Probably related to https://github.com/caskroom/homebrew-cask/issues/21729.

Same question I asked there. Do you have a `.curlrc`?

**Comment by vitorgalvao** [comment] 2016-06-12 11:09
Closing on account of no reply. Also see https://github.com/caskroom/homebrew-cask/issues/21729. The issue there was solved with a simple reboot.

**Closed by vitorgalvao** 2016-06-12 11:09 UTC
Labels: awaiting user reply

**Comment by henrylawson** [comment] 2016-06-12 23:19
Sorry for the late response, it is working for me now on both machines I saw the error. A lot has changed on them since I reported the issue. Both have definitely been rebooted since it was first observed.

Thanks for taking the time to look into this issue.

**Comment by vitorgalvao** [comment] 2016-06-12 23:28
Thank you for reporting back. Going to chalk this up to whatever the issue was that seemed to corrupt downloads and be resolved by a reboot.
