### ISSUE TITLE
Checksum for Cask 'filezilla' does not match.

### ISSUE THREAD

**Issue by maartenpaauw** [caskroom/homebrew-cask#44332] opened 2018-02-25 19:18 UTC
```
➜  ~ brew cask install filezilla
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Satisfying dependencies
==> Downloading https://downloads.sourceforge.net/filezilla/FileZilla_Client/3.31.0/FileZilla_3.31.0_macosx-x86.app.tar.bz2
Already downloaded: /Users/maartenpaauw/Library/Caches/Homebrew/Cask/filezilla--3.31.0.tar.bz2
==> Verifying checksum for Cask filezilla
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'filezilla' does not match.

Expected: 188e8d9af77dbcdd6176fb7eeca19083fff6f22e41331a1927c78c73c1faa769
Actual:   7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
File:     /Users/maartenpaauw/Library/Caches/Homebrew/Cask/filezilla--3.31.0.tar.bz2

To retry an incomplete download, remove the file above.
```

**Comment by SConaway** [comment] 2018-02-25 19:29
Worked fine for me. Try ` rm -f /Users/maartenpaauw/Library/Caches/Homebrew/Cask/filezilla--3.31.0.tar.bz2`

**Comment by vitorgalvao** [comment] 2018-02-25 19:34
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

I can confirm this works as expected, just like it did to @SConaway. Closing because you deleted the template without following the guides, that teach you to deal with this exact problem.

**Closed by vitorgalvao** 2018-02-25 19:34 UTC

**Comment by maartenpaauw** [comment] 2018-02-25 20:03
I don't get it. I've deleted the file. But I'm still getting the sha error.

Here is a recording:
[![asciicast](https://asciinema.org/a/NkA86z7SroB2Ln44t9Wh3PoUy.png)](https://asciinema.org/a/NkA86z7SroB2Ln44t9Wh3PoUy)

**Comment by vitorgalvao** [comment] 2018-02-25 20:06
@maartenpaauw Over half of that recording are commands that have no effect on homebrew-cask.

And again, [follow the guide](https://github.com/caskroom/homebrew-cask#reporting-bugs) or we won’t look at this.

**Comment by commitay** [comment] 2018-02-25 21:59
https://twitter.com/sfnet_ops/status/967809090545180672
> SourceForge is currently responding to a DDoS.  Please bear with us as we work to resolve the situation.

**Comment by maartenpaauw** [comment] 2018-02-25 22:14
@commitay Thanks, that explains a lot.
