### ISSUE TITLE
File exists

### ISSUE THREAD

**Issue by eric3zhao** [caskroom/homebrew-cask#16465] opened 2016-01-07 05:03 UTC
brew update
Updated Homebrew from 6488f169 to 4ae26624.

Updated 1 tap (caskroom/cask).
Error: File exists - (../../../Library/Taps/caskroom/homebrew-cask/man/man1/brew-cask.1, /usr/local/share/man/man1/brew-cask.1)

what the meaning of this error?

**Comment by jawshooah** [comment] 2016-01-07 05:04
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Closed by jawshooah** 2016-01-07 05:04 UTC

**Comment by eric3zhao** [comment] 2016-01-07 05:20
sorry,the error came out when I run 'brew update',so it should be report in brew project?
this is the new issues: https://github.com/Homebrew/homebrew/issues/47801

**Comment by jawshooah** [comment] 2016-01-07 05:22
No, you had the right repo the first time. The problem is that you didn't follow the steps in the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide, which would clear your issue right up.

**Comment by eric3zhao** [comment] 2016-01-07 05:33
It's ok now,thank you for your patience
