### ISSUE TITLE
citrix-receiver plugin error 403

### ISSUE THREAD

**Issue by mcnichol** [caskroom/homebrew-cask#18779] opened 2016-02-12 04:45 UTC
Getting an error 403 when trying to pull down citrix-receiver
```bash
$ brew cask install citrix-receiver
==> Downloading https://downloads.citrix.com/10820/CitrixReceiver12.1.dmg?__gda_

curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'citrix-receiver' with message: Download failed: https://downloads.citrix.com/10820/CitrixReceiver12.1.dmg?__gda__=1455232474_2e6dd1faf0ad4d99a5361e3ea75af357
```

**Comment by adidalal** [comment] 2016-02-12 05:38
Duplicate of https://github.com/caskroom/homebrew-cask/issues/18780

**Closed by adidalal** 2016-02-12 05:38 UTC
