### ISSUE TITLE
Bug: Exit with error, if the app is already there

### ISSUE THREAD

**Issue by tsparber** [caskroom/homebrew-cask#23377] opened 2016-08-02 21:43 UTC
### Description of enhancement

When installing an App that is already there, HBC should (in my opinion) exit with an error or warning.
### Justification

The current behavior with the output message of "success" is misleading, as the app (probably a newer version) has _not_ been successfully installed as it could not be moved.
### Example use case

```
$ brew cask install firefox
==> Downloading https://ftp.mozilla.org/pub/firefox/releases/48.0/mac/en-US/Firefox%2048.0.dmg
Already downloaded: /Users/tommy/Library/Caches/Homebrew/firefox-48.0.dmg
==> Verifying checksum for Cask firefox
==> It seems there is already an App at '/Applications/Firefox.app'; not moving.
🍺  firefox was successfully installed!
```

(well, actually it was not)

**Comment by vitorgalvao** [comment] 2016-08-02 22:01
Agreed. So much so, I consider the current behaviour a bug.

**Comment by frmendes** [comment] 2016-10-03 14:25
I've been tackling this but I have one question regarding the intended behavior: what should happen if `brew cask` is invoked with multiple apps and one of them already exists?

Exiting with an error would not install the remaining apps.

**Comment by reitermarkus** [comment] 2016-10-03 14:57
Ideally it would loop through all of them, and if one of them fails it is `rescue`d with an error message, but the loop continues. Of course, the exit code should be non-zero in this case.

**Comment by vitorgalvao** [comment] 2016-11-28 23:48
Closing in favour of https://github.com/Homebrew/brew/pull/1590.

**Closed by vitorgalvao** 2016-11-28 23:48 UTC
Labels: bug, core, ready to implement
