### ISSUE TITLE
Bug report: Failure to update caskroom/fonts and caskroom/versions

### ISSUE THREAD

**Issue by AnonymousESQFL** [caskroom/homebrew-cask#16031] opened 2015-12-22 04:33 UTC
(Remember to run `brew update; brew cleanup; brew cask cleanup` before reporting your issue. It usually fixes things!)—**Done!**

### Description of issue

For the past several weeks, I have been getting errors when running `brew update`. I'm getting errors stating `Failed to update tap: caskroom/fonts` and `Failed to update tap: caskroom/versions`. I'm reporting here because both errors reference caskroom. 

I'd appreciate any help/advice, as I am a total noob at the command line. Thanks!

### Output of `brew update --verbose`

````
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git status --untracked-files=all --porcelain 2>/dev/null

==> git rev-parse -q --verify HEAD
6c34fa12f57d8dfa24ab6eedd3012646a487240f
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
Already up-to-date.
==> git rev-parse -q --verify HEAD
6c34fa12f57d8dfa24ab6eedd3012646a487240f
==> git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null
refs/remotes/origin/master
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git status --untracked-files=all --porcelain 2>/dev/null

==> git rev-parse -q --verify HEAD
0848cb514737d036c4a308ce5de53caf6626851c
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
Already up-to-date.
==> git rev-parse -q --verify HEAD
0848cb514737d036c4a308ce5de53caf6626851c
==> git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null
refs/remotes/origin/master
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git status --untracked-files=all --porcelain 2>/dev/null

==> git rev-parse -q --verify HEAD
d49a8e5d1e49cedb9497f58b71a6a0ccfbbf710f
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
From https://github.com/caskroom/homebrew-fonts
 ! [rejected]        master     -> origin/master  (non-fast-forward)
Error: Failed to update tap: caskroom/fonts
==> git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null
refs/remotes/origin/master
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git status --untracked-files=all --porcelain 2>/dev/null

==> git rev-parse -q --verify HEAD
a2fbc90102cf16f6de40ee5536440392cee107a1
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
From https://github.com/caskroom/homebrew-versions
 ! [rejected]        master     -> origin/master  (non-fast-forward)
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
error: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log.
Automatic cleanup will not be performed until the file is removed.

warning: There are too many unreachable loose objects; run 'git prune' to remove them.

Error: Failed to update tap: caskroom/versions
==> git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null
refs/remotes/origin/master
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git status --untracked-files=all --porcelain 2>/dev/null

==> git rev-parse -q --verify HEAD
57257c3e53d1c9f2c55c239e24991a0acf2f38ab
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
Already up-to-date.
==> git rev-parse -q --verify HEAD
57257c3e53d1c9f2c55c239e24991a0acf2f38ab
Already up-to-date.
````

### Output of `brew doctor`

```
Your system is ready to brew.
```

### Output of `brew cask doctor`

```
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.2
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p645
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.5 (git revision 6c34f; last commit 2015-12-22)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew.git
==> Homebrew-cask Version:
0.60.0 (git revision 0848c; last commit 30 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files
0.00 megs
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
/usr/local/Library/Taps/caskroom/homebrew-fonts
/usr/local/Library/Taps/caskroom/homebrew-versions
==> Homebrew-cask Default Tap Cask Count:
2927
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
```

**Comment by jawshooah** [comment] 2015-12-22 04:43
This is a dupe of caskroom/homebrew-versions#1261.

Run `brew untap caskroom/versions && brew tap caskroom/versions` and you should be fine.

**Closed** 2015-12-22 04:43 UTC

**Comment by AnonymousESQFL** [comment] 2015-12-22 12:36
Awesome! Thank you very much. Happy holidays!


*—Aaron Alfano*
