### ISSUE TITLE
Bug report: installing google-chrome or firefox fails

### ISSUE THREAD

**Issue by pmcdaniel** [caskroom/homebrew-cask#21729] opened 2016-06-06 01:19 UTC
### Description of issue
When running `brew cask install google-chrome` I get an 
```
hdiutil: mount failed - Protocol wrong type for socket
Error: Empty plist input
```

I've seen similar issues reported (#9481), but they all appear to have been fixed, but I'm still see the issue on latest with OS X 10.11.
### Output of `brew cask install google-chrome --verbose`

```
[09:07:28] [~/.dotfiles] [master] -> brew cask install google-chrome --verbose
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-648) https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg -C 0 -o /Users/pmcdaniel/Library/Caches/Homebrew/google-chrome-latest.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 65.5M  100 65.5M    0     0  3184k      0  0:00:21  0:00:21 --:--:-- 1912k
==> No checksum defined for Cask google-chrome, skipping verification
==> hdiutil: mount failed - Protocol wrong type for socket
Error: Empty plist input
Error: Kernel.exit
```

### Output of `brew doctor`

```
Your system is ready to brew.
```

### Output of `brew cask doctor`

```
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 2cd8; last commit 2016-06-05)
Homebrew/homebrew-core (git revision afe70; last commit 2016-06-06)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-cask Version:
0.60.0 (git revision 74fb; last commit 13 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Users/pmcdaniel/Library/Caches/Homebrew
/Users/pmcdaniel/Library/Caches/Homebrew/Casks
2 files, 131M (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
3198
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="./bin:/usr/local/bin:/usr/local/sbin:/Users/pmcdaniel/.dotfiles/bin:/Users/pmcdaniel/.rbenv/shims:/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pmcdaniel/Toolchains/Android/tools:/Users/pmcdaniel/Toolchains/Android/platform-tools:/Users/pmcdaniel/Toolchains/Android-NDK:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
```

**Comment by vitorgalvao** [comment] 2016-06-07 16:14
I cannot reproduce this at all. `open $(brew --cache)` (to open the directory in the Finder). If you open the `dmg` there, does it also give an error?

**Comment by vitorgalvao** [comment] 2016-06-07 16:15
I cannot reproduce this at all. `open $(brew --cache)` (to open the directory in the Finder). If you open the `dmg` there, does it also give an error?

Probably related to https://github.com/caskroom/homebrew-cask/issues/21530.

Do you have a `.curlrc`?

**Comment by pmcdaniel** [comment] 2016-06-11 11:58
Sorry for taking so long with this reply.

I do not have a `.curlrc` file and attempting to open the .dmg from finder gives the following warning dialog:
![screen shot 2016-06-11 at 7 57 58 am](https://cloud.githubusercontent.com/assets/856681/15984946/4bc8898c-2faa-11e6-9c92-0bf6ee4eb3f0.png)

**Comment by pmcdaniel** [comment] 2016-06-11 12:01
In case this helps here is the output of `curl --version`:
```
[07:59:57] [~]  -> curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 
```

**Comment by vitorgalvao** [comment] 2016-06-11 14:41
Try this, then:

1. Manually download `https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg`.
2. Try to open it. If it fails, there’s something wrong with your connection/machine. If it succeeds, continue.
3. Rename the downloaded `dmg` to `google-chrome-latest.dmg`.
4. Open homebrew’s cache directory (`open "$(brew --cache)"`).
5. Put the `dmg` there.
6. Try `brew cask install google-chrome`.

**Comment by pmcdaniel** [comment] 2016-06-12 00:11
Ok I feel a little sheepish after all this, but after downloading the dmg manually it still failed with the above error.  Did a quick Google search of the above error from the dmg and the overwhelming suggestion was to reboot and try again...After a reboot everything worked 😄

**Comment by vitorgalvao** [comment] 2016-06-12 11:09
> After a reboot everything worked

Ah, the old “[have you tried turning it off and on again](https://www.youtube.com/watch?v=kb2gzteVNa4)”.

Glad to see it working. Closing.

**Closed by vitorgalvao** 2016-06-12 11:09 UTC
Labels: awaiting user reply
