### ISSUE TITLE
Need help implementing outdated verb

### ISSUE THREAD

**Issue by WitzHsiao** [caskroom/homebrew-cask#9403] opened 2015-02-03 09:43 UTC
Hey guys

I wanna implement `outdated` verb in homebrew-cask.
My idea is getting the version in the `Info.plist` in the content of apps and comparing with the version of Cask.
And now, I'm wondering how to get the version of Cask not just `:latest` in some DSL of Casks.
Thanks

**Comment by phinze** [comment] 2015-02-06 16:07
Hi @WitzHsiao - great to hear you're interested in contributing!

> And now, I'm wondering how to get the version of Cask not just :latest in some DSL of Casks.

Not quite sure what you're asking here. For Casks where we only have an un-versioned URL, the "version" from the perspective of Cask actually _is_ `:latest`.

So I'm not sure if I understand the strategy you're thinking of attempting here. Maybe if you can elaborate a bit more we can help you out further?

**Comment by WitzHsiao** [comment] 2015-02-08 13:01
Hi @phinze 
Thanks for your reply.
It's quite complicated. Is there a way to get the explicit version before install cask, not just `:latest`?

**Comment by phinze** [comment] 2015-02-08 13:27
Hey again!

A few core maintainers had a meeting in IRC yesterday about next steps for implementing `brew cask upgrade`, and we decided that I should get a version of `brew cask outdated` _without_ `:latest` support implemented. I'm working on that now. 

Here I'll push the WIP so you can track my progress if you like: https://github.com/caskroom/homebrew-cask/pull/9490

Sounds like you are interested in figuring out how to tackle `:latest` Casks, which so far we've decided to punt on. Our initial version of both `outdated` and `upgrade` will just refuse to work for `:latest` Casks.

You're right that for apps with an `Info.plist` we could parse a version from there, but the problem is that the only way to check for a _new_ version is to download and extract the whole thing again. Maybe you have another approach I haven't thought of though - new ideas are always welcome! :grinning: 

The other thing to mention here is that we have Big Plans for apps that self-update using the Sparkle framework. We plan on cask getting first class knowledge of updates and upgrades for these apps. It will be awesome! :fist:

**Comment by WitzHsiao** [comment] 2015-02-09 11:18
Cool beans!
I will look #9490 up, and see what can I do.
Thanks for your help. :+1:

**Comment by WitzHsiao** [comment] 2015-02-10 05:56
@phinze 
My first thought was that remove the `:latest` in DSL and strictly write down the explicit version. But I saw there are over 800 DSLs are using `:latest`. is it a good way to do it?

**Comment by phinze** [comment] 2015-02-10 13:47
@WitzHsiao All the `:latest` Casks have that set as the version because the URL they point to is also un-versioned, so there's no way for us to know when the version being served from that URL changes.

So you could theoretically capture all the explicit versions once, but then we'd need a plan for keeping them from drifting.

That's why we are capturing the `appcast` information, so we can start to support apps that use the [Sparkle](http://sparkle-project.org/) framework by automatically detecting the version updates they publish. But without a version publishing standard like Sparkle's `appcast`, you're looking at the prospect of regularly downloading every Cask to detect version changes, which seems too expensive to pursue.

**Comment by vitorgalvao** [comment] 2015-03-21 18:51
@WitzHsiao Do you still need further clarifications, or could we close this?

**Closed** 2015-04-21 16:17 UTC
Labels: waiting-user-reply
