### ISSUE TITLE
"brew cask edit [...]" fails with Error: No such file or directory - mate

### ISSUE THREAD

**Issue by pettai** [caskroom/homebrew-cask#8919] opened 2015-01-15 00:01 UTC
$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Updated Homebrew from e42906f8 to 52e2d557
[...]
Error: brew-cask 0.52.1 already installed
$ brew cask search yubi
==> Partial matches
yubikey-neo-manager		  yubikey-personalization-gui	    yubiswitch
$ brew cask edit yubiswitch
Error: No such file or directory - mate

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/utils.rb:138:in `exec'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/utils.rb:138:in `exec_editor'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli/edit.rb:18:in `exec_editor'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli/edit.rb:12:in `run'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/brew-cask-cmd.rb:18:in `<main>'

**Comment by pettai** [comment] 2015-01-15 00:05
Useful info 

$ brew cask doctor
==> OS X Release:
10.9
==> OS X Point Release:
10.9.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.52.1
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.52.1
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files
0.00 megs
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2231
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.52.1/rubylib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin13
/Library/Ruby/Site/2.0.0/universal-darwin13
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin:/opt/local/bin:/opt/local/sbin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LC_CTYPE="UTF-8"
==> Running As Privileged User:
No

**Comment by pettai** [comment] 2015-01-15 00:17
Ok, setting environment variable HOMEBREW_EDITOR solves it.
It would be useful if there was a check for that and a message that hints about this, instead of the current bail out and error message...

($ brew edit [...] works fine without HOMEBREW_EDITOR, while it will give you a suggestion to set it...)

**Comment by ndr-qef** [comment] 2015-01-15 00:46
Indeed, there has been an issue (previously reported as #8788) with env variables when launching editors. It will be fixed in the next release. (It was caused by the recent shuffling and stripping of large quantities of vestigial backend code.)

**Closed by ndr-qef** 2015-01-15 00:46 UTC
