### ISSUE TITLE
xattr 2.7 not compatible anymore

### ISSUE THREAD

**Issue by xavier7179** [caskroom/homebrew-cask#27294] opened 2016-12-01 09:29 UTC
It has been a while that some casks got stuck when try to install them due to xattr 2.7 compatibility... Is it possible to solve it within cask?

```
==> Verifying checksum for Cask filebot
==> Symlinking Binary 'filebot.sh' to '/usr/local/bin/filebot'
Error: Command failed to execute!

==> Failed command:
/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames (\"filebot\") /usr/local/Caskroom/filebot/4.7.5/FileBot.app/Contents/MacOS/filebot.sh

==> Standard Output of failed command:


==> Standard Error of failed command:
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

**Comment by vitorgalvao** [comment] 2016-12-03 16:26
Please follow the steps in [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).

What macOS version are you on? I could not reproduce this on either El Capitan or Sierra.

**Comment by vitorgalvao** [comment] 2016-12-04 16:16
Closing since I cannot reproduce and the steps in [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) were not followed.

From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.
> (…)
> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Closing for now because “drive-by bug reports” are common and many people just abandon their issues after a request for necessary information.

**Closed by vitorgalvao** 2016-12-04 16:16 UTC
Labels: awaiting maintainer feedback, awaiting user reply
