### ISSUE TITLE
Symlinking Binary fails

### ISSUE THREAD

**Issue by rednoah** [caskroom/homebrew-cask#17366] opened 2016-01-20 07:21 UTC
Whatever it is that `xattr` does, but it's probably pretty optional, so a warning message would suffice, rather than a failed install.

```
$ brew cask install filebot --force
==> Caveats
filebot requires Java 8. You can install the latest version with

  brew cask install java

==> Downloading http://downloads.sourceforge.net/project/filebot/filebot/FileBot
Already downloaded: /Library/Caches/Homebrew/filebot-4.6.1.tar.bz2
==> Verifying checksum for Cask filebot
==> Symlinking App 'FileBot.app' to '/Users/hackintosh/Applications/FileBot.app'
==> Symlinking Binary 'filebot.sh' to '/usr/local/bin/filebot'
Error: Command failed to execute!

==> Failed command:
["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "(\\\"filebot\\\")", "#<Pathname:/usr/local/bin/filebot>"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 655 exit 1>
```

**Comment by adidalal** [comment] 2016-01-25 16:10
Seems to be a bug on your end - no issues here unfortunately.

```
==> Caveats
filebot requires Java 8. You can install the latest version with

  brew cask install java

==> Downloading http://downloads.sourceforge.net/project/filebot/filebot/FileBot
######################################################################## 100.0%
==> Verifying checksum for Cask filebot
==> Symlinking App 'FileBot.app' to '/Applications/FileBot.app'
==> Symlinking Binary 'filebot.sh' to '/usr/local/bin/filebot'
🍺  filebot staged at '/opt/homebrew-cask/Caskroom/filebot/4.6.1' (12 files, 49M)
 [.../homebrew-cask/Casks] > 
```

**Comment by vitorgalvao** [comment] 2016-02-03 11:44
Can’t reproduce as well, so it seems indeed to be something in your setup. Have you tried [the usual sing-along](https://github.com/caskroom/homebrew-cask#reporting-bugs)?

Closing for now.

**Closed by vitorgalvao** 2016-02-03 11:44 UTC
Labels: bug, cask

**Comment by rednoah** [comment] 2016-02-04 12:02
Just forwarding the logs along for a n00b user. Feel free to close the issue if there's nothing you can do about it. ;)
