### ISSUE TITLE
Getting wrong number of arguments and cannot fix: 'brew cask '

### ISSUE THREAD

**Issue by alexozwald** [caskroom/homebrew-cask#41846] opened 2017-12-12 02:16 UTC
My issue doesn't seem to be as common as others who have had issues with the number of arguments. On mac os (high sierra) 10.13.2 using `brew cask` seems to return an error:
```
$ brew cask
Error: wrong number of arguments (given 2, expected 1)
```
rather than displaying a list of commands that can be used.

I noticed this by accidentally typing in half an argument and pressing enter, but I still think it's probably an issue. And some additional information (though it could have started before today):
```
$ brew cask --version
Homebrew-Cask 1.4.0
caskroom/homebrew-cask (git revision dde2c2; last commit 2017-12-12)
```

**Comment by commitay** [comment] 2017-12-12 02:18
Duplicate of https://github.com/caskroom/homebrew-cask/issues/41819

**Closed by commitay** 2017-12-12 02:18 UTC
