### ISSUE TITLE
Can optparse handle --verSIONs?

### ISSUE THREAD

**Issue by Amorymeltzer** [caskroom/homebrew-cask#16265] opened 2016-01-01 00:25 UTC
This is a weird one, but I think the issue is with `OptionParser` in [/lib/hbc/cli.rb#L149](https://github.com/caskroom/homebrew-cask/blob/71e3cdd201d59f5c4b82b42d7b7cba571bdf4f07/lib/hbc/cli.rb#L149).  Basically (`list` is just an example, every command behaves the same way):
````shell
$ brew cask list --v
Error: There is more than one possible option that starts with '--v' (expected output)

$ brew cask list --ve
$ brew cask list --ver
(list of casks, many columns) (expected output)

$ brew cask list --vers
$ brew cask list --versi
$ brew cask list --versio
$ brew cask list --version
brew Version (unexpected output)

$ brew cask list --versions
(list of casks, one column, with versions) (expected output)
````

AFAICT, it's in the `OptionParser` call that this happens (please, correct me if I'm wrong; I haven't looked into the optparse.rb source yet).  Is this a bug on their part?  I'd love someone to confirm, the presence of `brew` in the output makes me shaky.  If so, then perhaps another way of handling options is required.

---
I should add I'm on Mavericks (10.9), system ruby is `2.0.0p481`

**Comment by jawshooah** [comment] 2016-01-01 00:30
Not at a computer right now, but my guess is that Homebrew is pre-processing args before we can, and they intercept the `--version` flag.

**Comment by jawshooah** [comment] 2016-01-01 02:42
Ah, I didn't realize that `brew Version` was literally that text. Just tried it locally and got the same thing. Has absolutely nothing to do with Homebrew, so that's good.

The problem is very straightforward: we never intended for someone to pass `--version` to a subcommand like `list`, so we didn't configure `OptionParser` with a response.

There are two simple solutions: tell `OptionParser` what to do with the `--version` flag, or handle it specially elsewhere (like we [do now](https://github.com/caskroom/homebrew-cask/blob/71e3cdd201d59f5c4b82b42d7b7cba571bdf4f07/lib/hbc/cli.rb#L235), but earlier).

**Comment by Amorymeltzer** [comment] 2016-01-01 02:53
It just seems a really weird error case.  Where does "brew Version" come from, and why does it start at `--vers`?  The larger issue is really better error handling, but this is treated quite differently than any other option (I think).  `brew cask list --bacon` fails as you would expect, as does `brew cask info`.  The presence of a cask token doesn't make a difference, although a command like `zap` just drops a dead argument no problem.

**Comment by jawshooah** [comment] 2016-01-01 03:08
We can see what's happening if we take a look at `optparse.rb` and [this line in Homebrew](https://github.com/Homebrew/homebrew/commit/5a2292ff22d08b6c8b7c06bb15d6812577c977d2#L5):

```rb
  #
  # --version
  # Shows version string if Version is defined.
  #
  Officious['version'] = proc do |parser|
    Switch::OptionalArgument.new do |pkg|
      if pkg
        begin
          require 'optparse/version'
        rescue LoadError
        else
          show_version(*pkg.split(/,/)) or
            abort("#{parser.program_name}: no version found in package #{pkg}")
          exit
        end
      end
      v = parser.ver or abort("#{parser.program_name}: version unknown")
      puts v
      exit
    end
  end

...

  #
  # Returns version string from program_name, version and release.
  #
  def ver
    if v = version
      str = "#{program_name} #{[v].join('.')}"
      str << " (#{v})" if v = release
      str
    end
  end

...

  #
  # Version
  #
  def version
    @version || (defined?(::Version) && ::Version)
  end

...

  #
  # Program name to be emitted in error message and default banner, defaults
  # to $0.
  #
  def program_name
    @program_name || File.basename($0, '.*')
  end
```

`program_name` is just the program we've called, which is `brew`, so that makes sense.

To get the version, `OptionParser` first checks its own `@version` instance variable (accessible through its `attr_writer :version`, which we don't set), then `::Version` (which Homebrew extends in the line linked above).

See the difference when we directly run `cmd/brew-cask.rb` instead of `brew cask`:

```
$ cmd/brew-cask.rb list --version
brew-cask: version unknown
```

**Comment by jawshooah** [comment] 2016-01-01 03:12
This is all we need to do:

```rb
# in lib/hbc/cli.rb

def self.parser
  @parser ||= OptionParser.new do |opts|
    ...
  end
  @parser.version = Hbc.full_version
  @parser
end
```

**Comment by jawshooah** [comment] 2016-01-01 03:30
Well, I guess that depends on what we want the behavior to be.

When a user runs `brew cask <subcommand> --version`, should we:
  - print `Hbc.full_version` and exit (same as `brew cask --version`),
  - print `Hbc.full_version` and run the command as normal,
  - ignore the `--version` and run the command as normal,
  - or treat `--version` like any other positional argument after a subcommand (like `--bacon`, as you said)?

**Comment by Amorymeltzer** [comment] 2016-01-01 17:17
I lean toward the last; if it's wrong, it's wrong, no need to treat it differently.  2 isn't a bad idea, though.

**Comment by adityadalal924** [comment] 2016-01-01 20:45
Agreed with @Amorymeltzer here, as I don't see a particular burning need for `--version` anyways

**Comment by vitorgalvao** [comment] 2016-01-01 20:51
Tangentially related, https://github.com/caskroom/homebrew-cask/issues/5000. That is so old, though, some of those don’t even apply anymore. All of the “need to refactor X” issues fall a bit under that same umbrella, and I wouldn’t oppose to closing them all and keep refactoring things as they are needed, as we (mostly @jawshooah) have been doing.

**Comment by jawshooah** [comment] 2016-01-01 20:57
The points in #5000 are all still relevant (with `s/Cask/Hbc/g`), no need to close it. I've self-assigned to make sure it doesn't go forgotten.

**Closed** 2016-01-02 22:31 UTC
Labels: bug, core
