### ISSUE TITLE
install sourcetree error,help

### ISSUE THREAD

**Issue by CaiHuan** [caskroom/homebrew-cask#11108] opened 2015-05-10 13:51 UTC
==> Caveats
Cask sourcetree installs files under "/usr/local".  The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in homebrew-cask.

==> Downloading https://downloads.atlassian.com/software/sourcetree/SourceTree_2

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Download failed on Cask 'sourcetree' with message: Download failed: https://downloads.atlassian.com/software/sourcetree/SourceTree_2.0.5.2.dmg

**Comment by vitorgalvao** [comment] 2015-05-10 14:59
Can’t reproduce. Please [follow the instructions on opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by winkelsdorf** [comment] 2015-05-25 14:36
Can't reproduce too, installed SourceTree yesterday. Was either a probelmatic Cert Swap @Atlassian (unlikely) or is a Cert Store Issue on Users System. Closing?

**Closed** 2015-05-25 14:54 UTC
