### ISSUE TITLE
bittorrent-sync install error

### ISSUE THREAD

**Issue by mcandre** [caskroom/homebrew-cask#10755] opened 2015-04-21 02:45 UTC
When I try to install BitTorrent Sync with brew cask, I get errors.

**Trace**

```
$ brew cask install --verbose bittorrent-sync
==> Downloading https://download-cdn.getsyncapp.com/stable/osx/BitTorrent-Sync.dmg
Already downloaded: /Library/Caches/Homebrew/bittorrent-sync-latest.dmg
==> This subcommand requires root privileges: bsexec
Error: Empty plist input
```

**System**

```
$ brew doctor
Your system is ready to brew.

$ specs brew-cask brew os
Specs:

specs 0.17
https://github.com/mcandre/specs#readme

brew-cask --version
0.51.1

brew --version
0.9.5

system_profiler SPSoftwareDataType | grep 'System Version'
      System Version: OS X 10.10.3 (14D136)
```

**Comment by vitorgalvao** [comment] 2015-04-21 10:29
This is clearly a duplicate of #10731.

**Closed by vitorgalvao** 2015-04-21 10:29 UTC
