### ISSUE TITLE
Error: Cask 'ionic-lab' definition is invalid: Bad header line: parse failed

### ISSUE THREAD

**Issue by pkoppstein** [caskroom/homebrew-cask#16344] opened 2016-01-04 07:49 UTC
```
$ brew search iconic-lab
...
This formula was found in a tap:
Caskroom/cask/ionic-lab
To install it, run:
  brew install Caskroom/cask/ionic-lab

$ brew install Caskroom/cask/ionic-lab
==> brew cask install Caskroom/cask/ionic-lab
Error: Cask 'ionic-lab' definition is invalid: Bad header line: parse failed

$ brew --version
Homebrew 0.9.5 (git revision 077e0d; last commit 2016-01-04)
```

**Comment by jawshooah** [comment] 2016-01-04 10:02
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Closed by jawshooah** 2016-01-04 10:02 UTC

**Comment by pkoppstein** [comment] 2016-01-04 16:06
OK, running `brew uninstall --force brew-cask; brew update` did the trick; there was no clue that there has been a switch to a "new system".  Is that a bug of some kind?

**Comment by vitorgalvao** [comment] 2016-01-04 16:11
> there was no clue that there has been a switch to a "new system". Is that a bug of some kind?

[Huge bolded message at the top of the README](https://github.com/caskroom/homebrew-cask#homebrew-cask). Also, `brew-cask` itself outputted a message when you updated to the latest version.

**Comment by pkoppstein** [comment] 2016-01-04 16:52
@vitorgalvao - You might try to see things from a homebrew user's point of view. In short, I ran `brew update` (which gave no message or hint about having to uninstall brew-cask), and then the following commands, shown here with their output so you can see that there was again no message or hint about having to uninstall brew-cask:

```
$ brew install ionic-lab
Error: No available formula with the name "ionic-lab" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
Caskroom/cask/ionic-lab
To install it, run:
  brew install Caskroom/cask/ionic-lab

$ brew install Caskroom/cask/ionic-lab
==> brew cask install Caskroom/cask/ionic-lab
Error: Cask 'ionic-lab' definition is invalid: Bad header line: parse failed

```

**Comment by vitorgalvao** [comment] 2016-01-04 17:58
> You might try to see things from a homebrew user's point of view.

I am, since I’m also a homebrew user. Difference being I rarely run `brew update` without `brew upgrade`. Even if I didn’t, `brew update` always tells you what was updated.

To be clear, I’m not saying you’re at fault, here, far from it! I very much understand that since things work most of the time and there are always so many messages, we might miss important ones. This is one of the reasons I’ve always argued strongly to make sure our `caveats` section includes *only* messages important to the installation of the software, and nothing else.

My reply was only to address the notion that “there was no clue that there has been a switch”, as there are a multitude of steps that present thelseves before arriving at needing to open this issue:

+ [The aforementioned huge message](https://github.com/caskroom/homebrew-cask#homebrew-cask).
+ The message outputted by homebrew-cask itself.
+ The information of outdated packages from `homebrew update`.
+ Our [reporting bugs guidelines](https://github.com/caskroom/homebrew-cask#reporting-bugs).
+ Our [issue templates](https://github.com/caskroom/homebrew-cask#questions-wanna-chat).
+ [Searching past issues](https://github.com/caskroom/homebrew-cask/search?q=definition+is+invalid%3A+Bad+header+line&type=Issues&utf8=%E2%9C%93).

Notice how **the majority of our already small README is about reporting bugs** (and quickly fixing the most common ones). That in addition to other places in the documentation and the app itself. We’re not yet stable (and always tried to make that clear) and have breakages, and a large section of people don’t read help and guidelines. We spend a non-trivial amount of time discussing and improving those help sections so they’re easier to find.

Again, I’m not at all saying you’re at fault. I understand (don’t necessarily agree with it, but understand it) the drive that leads to taking the (seemingly) faster route of directly asking for help when you see something stopped working and just want it to work again. However, saying there “was no clue” is just plain false. There are limits to what we can do to inform you with our available time and without reducing the experience of other users, and we already have a multitude (read “absurd amount”) of *repeated* information geared for the same simple task of just saying “can you please make sure you have the latest version before saying there’s a bug?”. That’s not an unreasonable request, but needs to be made an unreasonable amount of times.

**Comment by pkoppstein** [comment] 2016-01-04 20:15
@vitorgalvao - Thanks for your long reply.  Everything you say is very reasonable and I appreciate your taking the time to explain things, but I think you're missing a key point -- one that might even save you and your colleagues a great deal of time and frustration.  In a nutshell, I think it would help if the error message that I did see ("Error: Cask 'ionic-lab' definition is invalid: Bad header line: parse failed") were a little more expansive.  (In fact, one might even say the existing error message as presented is misleading, but I won't press the point.)  

Perhaps the error message being of limited use is a "homebrew" problem rather than a "cask" problem; if so, then maybe the root issue here is the integration of homebrew and cask, in which case I hope it will somehow be pushed upstream. 

Regarding your comment about `brew update`, I'd like to point out that I had dutifully run `brew update` before attempting the installation of ionic-lab, and in fact I still have a copy of the output it gave. The first few lines were:
```
Updated 10 taps (caskroom/cask, homebrew/binary, homebrew/boneyard, homebrew/dupes, homebrew/emacs, homebrew/php, homebrew/python, homebrew/science, homebrew/versions, homebrew/x11).
```
There was nothing in the output about having to reinstall anything.  Perhaps the warning you have in mind was given during a previous run of `brew update`, but if anyone was expecting homebrew users to be attentive to (and remember) details that are irrelevant to the then-current task when running `brew update`, that's just asking for trouble.

Now that you've pointed out that there is a cask README page, I can of course see the warning, but as I said, I'm just a homebrew user who was following the homebrew instructions (as shown above). Of course I did search for help (using google), but nothing brought me to the cask README page or any of the warnings you mention.  Yes, I could have spent more time searching, but I hope you will agree that it is a better use of one's time to try to find the root cause of a problem that potentially affects many others than to google away indefinitely.

**Comment by jawshooah** [comment] 2016-01-04 22:49
> I think it would help if the error message that I did see ("Error: Cask 'ionic-lab' definition is invalid: Bad header line: parse failed") were a little more expansive.

The problem is that you were running an old version of `brew-cask`, which is where the error message is defined, so we have no way of modifying it. If you're running outdated code, there's nothing we can do to change it other than to tell you to upgrade.

**Comment by vitorgalvao** [comment] 2016-01-04 23:23
> Of course I did search for help (using google), but nothing brought me to the cask README page or any of the warnings you mention. Yes, I could have spent more time searching, but I hope you will agree that it is a better use of one's time to try to find the root cause of a problem that potentially affects many others than to google away indefinitely.

We’re evolving so fast (and have still more changes planned) that what you find via googling has a good chance of being outdated. I’d also argue that googling is the worse method to search for an error when you have access to the repo. If there’s a place where an error will be throughly discussed and solved it’s in the repo’s issues, not on a random website.

**Comment by pkoppstein** [comment] 2016-01-04 23:38
@jawshooah wrote: 

> The problem is that you were running an old version of brew-cask ...

Yes, that's why I said that (from a homebrew user's point of view), the problem is likely one of integration (of homebrew and brew-cask).  That is, the command that gave the not-so-helpful error message was a brew command:

brew install Caskroom/cask/ionic-lab

So it would be helpful if the "brew" command did the relevant checking.

**Comment by jawshooah** [comment] 2016-01-04 23:45
The error message was generated by `brew-cask`. Homebrew delegates to `brew-cask` if they detect you are trying to install a cask rather than a formula.

What might be helpful would be for Homebrew to check whether a legacy install of `brew-cask` exists and fail/warn if so.

**Comment by pkoppstein** [comment] 2016-01-04 23:49
@vitorfalvao wrote:
> I’d also argue that googling is the worse method to search for an error ...

Fair enough, but even now, when I enter the query:

> is:issue ionic-lab definition is invalid 

in the search box at https://github.com/caskroom/homebrew-cask/issues

nothing comes up (except of course for #16344).

And how many users of homebrew would even think of searching at homebrew-cask when they're just following brew-provided instructions?  (How many homebrew users understand the distinctions between "Caskroom", "homebrew-cask" and "cask"?)

**Comment by pkoppstein** [comment] 2016-01-04 23:56
@jawshooah wrote:

> What might be helpful would be for Homebrew to check whether a legacy install of brew-cask exists and fail/warn if so.

Exactly.   Thank you!  Would someone on the homebrew-cask team be willing to take up the matter?

**Comment by vitorgalvao** [comment] 2016-01-05 00:00
> Fair enough, but even now, when I enter the query:

> > is:issue ionic-lab definition is invalid

There’s a specific app name in there. It seems to me a reasonable search (even if was the second) would be to not include the app’s name, and see if it was a more generic issue ([which is a fruitful search](https://github.com/caskroom/homebrew-cask/search?q=definition+is+invalid%3A+Bad+header+line&type=Issues&utf8=%E2%9C%93)).

> And how many users of homebrew would even think of searching at homebrew-cask when they're just following brew-provided instructions?  (How many homebrew users understand the distinctions between "Caskroom", "homebrew-cask" and "cask"?)

From all my time at the project, I’d say the majority, and only growing in ratio. The question is irrelevant, though, *you* knew to ask here. I also [don’t see a single issue on homebrew related to this](https://github.com/Homebrew/homebrew/search?q=definition+is+invalid%3A+Bad+header+line&type=Issues&utf8=%E2%9C%93) (here, there are multiple).

> > What might be helpful would be for Homebrew to check whether a legacy install of brew-cask exists and fail/warn if so.

> Exactly. Thank you! Would someone on the homebrew-cask team be willing to take up the matter?

Wrong place to ask. Also, I don’t think they will, nor do I think they should. We now update automatically, this will only become less of an issue over time.

**Comment by jpz** [comment] 2016-01-07 18:19
This is really hidden from the users.  I've been looking for around 20 minutes to work out why `brew cask install virtualbox` was not working for me.  

Appreciate the big bold message here - https://github.com/caskroom/homebrew-cask#homebrew-cask - not easy for the end users to discover however.  With best intent, my message is friendly feedback on discoverability and how the change may affect other similar users that will struggle with this.

**Comment by jawshooah** [comment] 2016-01-07 18:25
It is literally plastered all over our README, aside from the giant bold message at the top. Scroll down to Reporting Bugs.

And to be honest, I don't understand how people don't search issues first before posting their own. Just try searching for "parse failed" or "bad header line". we've had to regurgitate the same answers again and again because users don't look at the README and don't use the search feature. And frankly, that's not our fault.

**Comment by jpz** [comment] 2016-01-07 18:36
I did read the Readme - it just took me 20 minutes to find it.  If it were possible for the console usage to report the same message, it might be of utility to many users that don't frequent the GitHub repo.

I appreciate the wonderful work you all contribute with homebrew btw.  I am not complaining and I am actually thankful ;)

**Comment by vitorgalvao** [comment] 2016-01-07 18:45
@jpz Read this issue. [There’s a clear reason we couldn’t show you the message you want](https://github.com/caskroom/homebrew-cask/issues/16344#issuecomment-168836594), it’s a [catch-22](https://en.wikipedia.org/wiki/Catch-22_(logic)).

Even so, the message was [yet further improved](https://github.com/caskroom/homebrew-cask/pull/16368) to catch more cases. We’ve done everything we reasonably can. The good news is that the more people upgrade, the less this will ever happen (since everyone will always be seamlessly up-to-date).

There’s no sense in beating the topic to death, though. As it is, this issue has a full discussion and through explanations on the topic. Locking.
