### ISSUE TITLE
wkhtmltopdf fails to install

### ISSUE THREAD

**Issue by JaKXz** [caskroom/homebrew-cask#24143] opened 2016-08-29 19:20 UTC
```
$ brew cask install wkhtmltopdf
==> Caveats
Cask wkhtmltopdf installs files under "/usr/local". The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in Homebrew-Cask.

==> Satisfying dependencies
complete
==> Downloading http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_osx-cocoa-x86-64.pkg
######################################################################## 100.0%
==> Verifying checksum for Cask wkhtmltopdf
==> Running installer for wkhtmltopdf; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> sudo: sorry, you are not allowed to preserve the environment
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/usr/local/Caskroom/wkhtmltopdf/0.12.3/wkhtmltox-0.12.3_osx-cocoa-x86-64.pkg>", "-target", "/"]

==> Standard Output of failed command:


==> Standard Error of failed command:
sudo: sorry, you are not allowed to preserve the environment


==> Exit status of failed command:
#<Process::Status: pid 31282 exit 1>
```

<details>
<summary>`$ brew config`</summary>
```
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8e29cf1b1d39f5d86aaeb702597aa34d97cd763a
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1727689a384cf97aba11b580e2a6fef6217bcc68
Core tap last commit: 56 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/jasonkurian/.rvm/rubies/ruby-2.1.6/bin/ruby
Java: N/A
OS X: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A
```
</details>

**Comment by adidalal** [comment] 2016-08-30 01:52
That's a `sudo` error, are you an admin?

Try a `sudo echo "Thanks"` and retry

Or if all else fails, see if running the pkg installer manually works.

**Comment by JaKXz** [comment] 2016-08-30 23:04
I am definitely an admin on my machine, and the workaround I used is the
package installer from the website. I'd prefer to have it installed via
homebrew though, since I update homebrew frequently.

**Comment by JaKXz** [comment] 2016-09-05 19:31
@adidalal any updates? Thoughts?

**Comment by JaKXz** [comment] 2016-09-09 19:09
@adidalal seeing the same issue with `vagrant`, and I've been able to use `brew cask install` for 
<details>
<summary>some other apps.</summary>
```
$ brew cask list --versions
anatine 0.5.1
appcleaner 3.3
atom 1.9.9
caprine 1.5.0
flux 37.7
github-desktop 220
google-play-music-desktop-player 3.5.0
shiftit 1.6.3
sourcetree 2.3.1
```
</details>

**Comment by adidalal** [comment] 2016-09-09 23:39
Mind posting the output of brew cask doctor?

**Comment by JaKXz** [comment] 2016-09-10 04:58
https://gist.github.com/anonymous/1be898827e0f11551b5b09304a2978a8

Sorry I should have posted that earlier. Thanks for your help so far :)

**Comment by vitorgalvao** [comment] 2016-09-11 08:18
> I'd prefer to have it installed via homebrew though, **since I update homebrew frequently**.

[emphasis mine] But we don’t update your apps, so for the foreseeable future, there’s no difference.

I cannot reproduce this error at all with either `wkhtmltopdf` or `vagrant`. Can you, @adidalal?

**Comment by adidalal** [comment] 2016-09-11 14:35
Unfortunately not - I'm thinking permissions issue but don't really know.

**Comment by vitorgalvao** [comment] 2016-09-11 14:42
> sudo: sorry, you are not allowed to preserve the environment

This is the problem, and a message [given by the OS, not us](https://superuser.com/questions/636283/how-to-allow-user-to-preserve-environment-with-sudo).

As such, and since we maintainers cannot reproduce, I’m going to close this. The issue is with your configuration, not HBC itself.

**Closed by vitorgalvao** 2016-09-11 14:42 UTC
Labels: awaiting maintainer feedback

**Comment by JaKXz** [comment] 2016-09-11 16:32
Fair enough. Thanks.

**Comment by tmerrifi** [comment] 2016-11-22 05:20
got to /etc/sudoers and look for a line specifically for "/usr/sbin/installer" make sure to add SETENV: there.
