### ISSUE TITLE
Unable to add applications to dock in El Capitan

### ISSUE THREAD

**Issue by michael-keefe** [caskroom/homebrew-cask#18942] opened 2016-02-16 18:28 UTC
I've recently done a clean install of El Cap, and installed most of my apps via caskroom, but have found that I can't add any of the apps to the dock from either ~/Applications or by dragging them from Launchpad.

**Comment by adidalal** [comment] 2016-02-16 18:59
Duplicate of https://github.com/caskroom/homebrew-cask/issues/14129. Any `.app` won't cab't be added to the left-hand side of the dock because it's a symlink.

Resolution still the same, unfortunately - when the install behavior changes, a lot of these minor problems will go away.

That being said, I also like certain applications pinned in my dock, and my (bad) solution is to just not use Caskroom for the one app where I want I on my Dock (Sublime Text 3)

**Closed by adidalal** 2016-02-16 18:59 UTC

**Comment by miccal** [comment] 2016-02-16 20:59
If you right-click the app in `~Applications` and select `Show Original`, Finder will take you to the folder containing the `.app` which you can then add to the dock.

**Comment by adidalal** [comment] 2016-02-16 21:09
Thanks, @miccal!

**Comment by michael-keefe** [comment] 2016-02-16 21:54
I thought about the 'show original' option... But will this not break when
an app updates? A similar solution is to launch the app, right click on the
dock icon and choose 'keep in dock'.

On a related note, can anyone think of a reason for Apple to have disabled
symlinks in the dock?
