### ISSUE TITLE
Error: It seems the symlink source is not there: couchbase-server-community

### ISSUE THREAD

**Issue by arunt4ever** [caskroom/homebrew-cask#19392] opened 2016-03-02 04:30 UTC

**Comment by adidalal** [comment] 2016-03-02 04:34
This error is not a bug, it's caused by an update to how `homebrew-cask` works. Details can be found [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

To fix the issue, please run:
```bash
brew update; brew cleanup; brew cask cleanup
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)

**Comment by adidalal** [comment] 2016-03-02 04:35
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Closed by adidalal** 2016-03-02 04:34 UTC
