### ISSUE TITLE
Bug report: jahshaka fails to install

### ISSUE THREAD

**Issue by dionyziz** [caskroom/homebrew-cask#19886] opened 2016-03-17 11:38 UTC
(Remember to run `brew update; brew cleanup; brew cask cleanup` before reporting your issue. It usually fixes things!)

Done, did not fix things.

### Description of issue
jahshaka fails to install

### Output of `brew cask <command> --verbose`

```
[       0] dionyziz@Dionysiss-MacBook-Pro ~ % brew cask install --verbose jahshaka
==> Downloading http://downloads.sourceforge.net/sourceforge/jahshakafx/Jahshaka-binary/2.0/jahshaka-2.0-osx-intel.dmg
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-645) http://downloads.sourceforge.net/sourceforge/jahshakafx/Jahshaka-binary/2.0/jahshaka-2.0-osx-intel.dmg -C 0 -o /Library/Caches/Homebrew/jahshaka-2.0.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   379    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 37.0M  100 37.0M    0     0  1785k      0  0:00:21  0:00:21 --:--:-- 2181k
==> Verifying checksum for Cask jahshaka
==> Running installer for jahshaka; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is Jahshaka v2.0
==> installer: Installing at base path /
==> installer:PHASE:Preparing for installation…
==> installer: The install failed (The Installer could not install the software because there was no software found to install.)
==> 2016-03-17 21:05:36.359 installer[99533:3661527] Package /opt/homebrew-cask/Caskroom/jahshaka/2.0/jahshaka-2.0.mpkg uses a deprecated pre-10.2 format (or uses a newer format but is invalid).
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/jahshaka/2.0/jahshaka-2.0.mpkg>", "-target", "/", "-verboseR"]

==> Output of failed command:
installer: Package name is Jahshaka v2.0
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer: The install failed (The Installer could not install the software because there was no software found to install.)


==> Exit status of failed command:
#<Process::Status: pid 99532 exit 1>
Error: Kernel.exit
```

### Output of `brew doctor`

```
[       0] dionyziz@Dionysiss-MBP ~ % brew doctor
Your system is ready to brew.
```

### Output of `brew cask doctor`

```
[       0] dionyziz@Dionysiss-MBP ~ % brew cask doctor
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.3
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p645
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.5 (git revision 7e7f; last commit 2016-03-18)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.60.0 (git revision 1d629; last commit 2 hours ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files, 0B
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
3021
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/local/sbin:/usr/local/heroku/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/usr/local/git/bin:/Users/dionyziz/bin:.:/Users/dionyziz/.rvm/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LC_CTYPE="UTF-8"
==> Running As Privileged User:
No
```

**Comment by adidalal** [comment] 2016-03-17 15:11
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by dionyziz** [comment] 2016-03-17 19:06
Edited.

**Comment by adidalal** [comment] 2016-03-17 21:27
Don't see the edit, but reopening in case it's an issue on my end

**Comment by vitorgalvao** [comment] 2016-03-18 01:26
@adidalal Not just you. There was no edit.

**Comment by dionyziz** [comment] 2016-03-18 18:34
I edited the description to make the command `--verbose`. Do you not see this edited version?

**Comment by vitorgalvao** [comment] 2016-03-18 18:59
> I edited the description to make the command `--verbose`.

That’s not the only thing the guide @adidalal pointed you asks. It points to [a bug reporting template](https://github.com/caskroom/homebrew-cask/issues/new?title=Bug%20report%3A&body=%28Remember%20to%20run%20%60brew%20update%3B%20brew%20cleanup%3B%20brew%20cask%20cleanup%60%20before%20reporting%20your%20issue.%20It%20usually%20fixes%20things%21%29%0A%0A%23%23%23%20Description%20of%20issue%0A%0A%0A%0A%23%23%23%20Output%20of%20%60brew%20cask%20%3Ccommand%3E%20--verbose%60%0A%0A%60%60%60%0A%28paste%20output%20here%29%0A%60%60%60%0A%0A%23%23%23%20Output%20of%20%60brew%20doctor%60%0A%0A%60%60%60%0A%28paste%20output%20here%29%0A%60%60%60%0A%0A%23%23%23%20Output%20of%20%60brew%20cask%20doctor%60%0A%0A%60%60%60%0A%28paste%20output%20here%29%0A%60%60%60%0A) that must be filled.

**Comment by dionyziz** [comment] 2016-03-18 19:45
Sorry, I missed that link. Does it look better now?

**Comment by vitorgalvao** [comment] 2016-03-18 20:26
Yes, thank you.

**Comment by vitorgalvao** [comment] 2016-03-19 23:20
I was able to reproduce the error.

**Comment by vitorgalvao** [comment] 2016-06-12 11:24
Downloaded the software and tried to install it manually. This was the result.
![screen shot 2016-06-12 at 04 22 25](https://cloud.githubusercontent.com/assets/1699443/15990857/782d7444-3098-11e6-8c3f-f9e1e7968809.png)

Seems to be an upstream problem, not an HBC problem. Will remove the cask.

**Closed** 2016-06-12 11:24 UTC
Labels: bug, cask
