### ISSUE TITLE
Bug report: Cask terminates with Error: cannot load such file -- english

### ISSUE THREAD

**Issue by schanzel** [caskroom/homebrew-cask#22595] opened 2016-07-05 09:17 UTC
#### Description of issue

Since today, every call of brew cask [whatever] ends with the error message `Error: cannot load such file -- english`

This might be related to http://stackoverflow.com/questions/27294172/loaderror-cannot-load-such-file-english

I'm in fact running homebrew on a case-sensitive filesystem.

<details><summary>Output of `brew cask cleanup --verbose`</summary>

```
Error: cannot load such file -- english
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:19:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:12:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:23:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Warning: The filesystem on / appears to be case-sensitive.
The default OS X filesystem is case-insensitive. Please report any apparent problems.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
Error: cannot load such file -- english
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:19:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:12:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:23:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
```
</details>

**Comment by schanzel** [comment] 2016-07-05 11:56
Update: the change on lib/hbc/cli/style.rb:1 introduced by 11eedac seems to be the culprit.
Changing
```ruby
require "english"
```
to
```ruby
require "English"
```
solves the problem.

**Comment by Eightyplus** [comment] 2016-07-05 12:08
Can you specify the full path? I have the same problem, do you think it is due to 'case-insensitive' (which is also the setup I'm running with)?

**Comment by Eightyplus** [comment] 2016-07-05 12:10
Oh, this file /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb
Works for me as well!

**Comment by adidalal** [comment] 2016-07-05 12:26
Thanks for the bug report and PR - I've pushed the fix, so mind updating and ensuring that the issue is resolved?

Feel free to comment back if it isn't, but as I'm on a case-insensitive system I'll have to let one of the other maintainers take a look.

**Closed by adidalal** 2016-07-05 12:26 UTC

**Comment by schanzel** [comment] 2016-07-05 12:27
The issue is solved for me, Cask works as expected after a `brew up`. Thank you!
