### ISSUE TITLE
uninstall launchctl runs without sudo

### ISSUE THREAD

**Issue by fudgefr** [caskroom/homebrew-cask#36086] opened 2017-07-02 15:17 UTC
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

- Installed docker through `brew cask install docker`.
- fiddled around with docker, then decided to remove it.
- launched `brew cask uninstall docker`, got an error.

#### Output of your command with `--verbose --debug`

```shell
# brew cask uninstall docker --verbose --debug
==> Uninstalling Cask docker
==> Uninstalling Cask docker
==> Un-installing artifacts
==> Determining which artifacts are present in Cask docker
==> 3 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007fc15a898eb0>
#<Hbc::Artifact::App:0x007fc15a898e10>
#<Hbc::Artifact::Zap:0x007fc15a898ca8>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for docker; your password may be necessary
==> Removing launchctl service com.docker.helper
==> Executing: ["/bin/launchctl", "list", "com.docker.helper"]
==> Executing: ["/bin/launchctl", "unload", "-w", "--", "com.docker.helper"]
==> /Users/joe/Library/Containers/com.docker.helper/Data: Path not searched for services
==> /Users/joe/Library/Containers/com.docker.helper/Container.plist: Invalid property list
==> Executing: ["/bin/rm", "-f", "--", "com.docker.helper"]
==> rm: com.docker.helper: is a directory
Error: Command failed to execute!

==> Failed command:
/bin/rm -f -- com.docker.helper

==> Standard Output of failed command:


==> Standard Error of failed command:
rm: com.docker.helper: is a directory


==> Exit status of failed command:
#<Process::Status: pid 67320 exit 1>
Error: Uninstall incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```shell 
brew cask doctor                                                                                                                                                          
==> Homebrew-Cask Version
Homebrew-Cask 1.2.3-121-gb552908490
caskroom/homebrew-cask (git revision b79d50; last commit 2017-07-02)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3653 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
PATH="/usr/local/opt/ruby/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:~/.antigen/bundles/robbyrussell/oh-my-zsh/lib:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/python:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/osx:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/lein:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:~/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

Would be happy to help if needed!

**Comment by commitay** [comment] 2017-07-02 21:59
Please try:
```
sudo launchctl remove com.docker.helper

sudo launchctl remove com.docker.vmnetd

brew cask uninstall docker
```

**Comment by fudgefr** [comment] 2017-07-03 18:08
Yep, it works, thanks!

```shell
brew cask uninstall docker
==> Uninstalling Cask docker
==> Running uninstall process for docker; your password may be necessary
==> Removing launchctl service com.docker.helper
==> Removing launchctl service com.docker.vmnetd
==> Removing files:
/Library/PrivilegedHelperTools/com.docker.vmnetd
==> Removing App '/Applications/Docker.app'.
```

Does that mean something is missing in the formula?

By the way, this is a hell of a tool you are building, thanks for your hard work.

**Comment by commitay** [comment] 2017-07-03 21:20
> Does that mean something is missing in the formula?

No, this might be an issue with the core.

This is the third time I've seen this reported in the last two weeks. https://github.com/caskroom/homebrew-cask/issues/35977 https://github.com/caskroom/homebrew-cask/issues/35665

Ping @vitorgalvao @reitermarkus

**Comment by commitay** [comment] 2017-07-03 22:55
I've updated the title of the issue.

**Comment by fudgefr** [comment] 2017-07-04 18:42
Yep, it works, thanks!

```shell
brew cask uninstall docker
==> Uninstalling Cask docker
==> Running uninstall process for docker; your password may be necessary
==> Removing launchctl service com.docker.helper
==> Removing launchctl service com.docker.vmnetd
==> Removing files:
/Library/PrivilegedHelperTools/com.docker.vmnetd
==> Removing App '/Applications/Docker.app'.
```

Does that mean something is missing in the formula?

By the way, this is a hell of a tool you are building, thanks for your hard work.

**Comment by commitay** [comment] 2017-08-27 02:17
I've have been unable to reproduce this error and there hasn't been any new reports from users who have encountered this issue. Closing.

**Closed by commitay** 2017-08-27 02:17 UTC
Labels: awaiting maintainer feedback
