### ISSUE TITLE
Bug report: LogMeIn-Hamachi Cask cannot find downloaded ZIP file

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#26912] opened 2016-11-18 18:54 UTC
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue

When attempting to install the LogMeIn Hamachi Cask, the download completes successfully but is not found by homebrew-cask. Some investigation has determined that although the ZIP file downloads to `brew --cache`/Cask/logmein-hamachi--latest.zip, the Cask looks for it at /usr/local/Caskroom/logmein-hamachi/latest/`brew --cache`/cask/logmein-hamachi--latest.zip. It cannot find it there, so the installation fails.

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
==> Downloading https://secure.logmein.com/LogMeInHamachi.zip
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.1-31-g7853406fb4 (Macintosh; Intel macOS 10.12.1) curl/7.49.1 https://secure.logmein.com/LogMeInHamachi.zip -C 0 -o /Users/username/Library/Caches/Homebrew/Cask/logmein-hamachi--latest.zip.incomplete --silent
==> No checksum defined for Cask logmein-hamachi, skipping verification
Error: No such file or directory - /usr/local/Caskroom/logmein-hamachi/latest/`brew --cache`/cask/logmein-hamachi--latest.zip
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/criteria.rb:17:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/criteria.rb:17:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/criteria.rb:17:in `magic_number'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/ttf.rb:8:in `me?'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container.rb:55:in `block in for_path'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container.rb:53:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container.rb:53:in `find'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container.rb:53:in `for_path'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/nested_container.rb:16:in `extract'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/nested_container.rb:7:in `block in install_phase'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/nested_container.rb:7:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:133:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:130:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:130:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:73:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:110:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit

```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Your system is ready to brew.

```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.12.1
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.1-31-g7853406fb4
Homebrew/homebrew-core (git revision ee95; last commit 2016-11-18)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.1-31-g7853406fb4
caskroom/homebrew-cask (git revision 2821; last commit 2016-11-18)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/accountname/Library/Caches/Homebrew/Cask
1 files, 5.3M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions
==> Homebrew-Cask Default Tap Cask Count:
3438
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Library/TeX/texbin:/usr/local/sbin:/usr/local/go/bin:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"

```
</details>

**Comment by miccal** [comment] 2016-11-19 00:21
It installs fine for me - the only difference I see between your `brew cask install logmein-hamachi --verbose` and mine is that your says `1.1.1-31-g7853406fb4 (Macintosh; Intel macOS 10.12.1)` while mine says `--user-agent Homebrew/1.1.1 (Macintosh; Intel macOS 10.12.1)`.

Could you please run `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update` and try again?

**Comment by Saklad5** [comment] 2016-11-19 03:47
Still happening.

**Comment by miccal** [comment] 2016-11-19 03:56
What is the output of `brew --version` now?

**Comment by Saklad5** [comment] 2016-11-19 03:58
`Homebrew 1.1.1-31-g7853406fb4
Homebrew/homebrew-core (git revision f65b; last commit 2016-11-18)`

**Comment by miccal** [comment] 2016-11-19 04:35
Strange, as I said it installs fine for me and comparing your `brew cask doctor` output with mine, the only difference is the version of Brew as the output of `brew --version` for me is:
```
Homebrew 1.1.1
Homebrew/homebrew-core (git revision f65b; last commit 2016-11-18)
```

**Comment by vitorgalvao** [comment] 2016-11-19 13:03
I also cannot reproduce.

**Comment by miccal** [comment] 2016-11-19 13:06
@vitorgalvao is your `brew --version` the current release (1.1.1) or have you got `HOMEBREW_DEVELOPER` set so you get the absolute latest version of Homebrew?

**Comment by vitorgalvao** [comment] 2016-11-19 14:11
@miccal I have the same (similar) as @Saklad5:

```
Homebrew 1.1.1-31-g7853406
Homebrew/homebrew-core (git revision ee95; last commit 2016-11-18)
```

**Comment by miccal** [comment] 2016-11-19 14:18
Thanks - I was thinking that the problem may have been caused by a recent commit to Homebrew since the last release, but that is clearly not the case if you are not seeing the same issue.

**Comment by miccal** [comment] 2016-11-19 14:37
@Saklad5 in your output of `brew cask install logmein-hamachi --verbose` you have the line:
```
Error: No such file or directory - /usr/local/Caskroom/logmein-hamachi/latest/`brew --cache`/cask/logmein-hamachi--latest.zip
```
where in your case \`brew --cache\` is `/Users/accountname/Library/Caches/Homebrew/Cask`.

Are you sure this line is correct, because the directory path would then have a double slash:
```
/usr/local/Caskroom/logmein-hamachi/latest//Users/accountname/Library/Caches/Homebrew/Cask/cask/logmein-hamachi--latest.zip
```
which clearly does not exist.

**Comment by Saklad5** [comment] 2016-11-19 15:04
I redirected stdout and stderr to a file to make sure nothing was copied incorrectly. The only change I made was to the account name.

I believe what you are describing is in fact the problem, though I'm not sure why such behavior is not reproduced on @vitorgalvao's computer.

**Comment by adidalal** [comment] 2016-11-19 18:07
Can't reproduce:

```
[.../homebrew-cask/Casks] > cask install --verbose logmein-hamachi
==> Downloading https://secure.logmein.com/LogMeInHamachi.zip
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.1 (Macintosh; Intel macOS 10.11.6) curl/7.43.0 https://secure.logmein.com/LogMeInHamachi.zip -C 0 -o /Users/aditya/Library/Caches/Homebrew/Cask/logmein-hamachi--latest.zip.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5410k  100 5410k    0     0  5387k      0  0:00:01  0:00:01 --:--:-- 5389k
```

**Comment by vitorgalvao** [comment] 2016-11-19 18:24
@adidalal I’ll remove the `bug` label, since so far this has not been proven a bug. So far it looks like a specific problem in @Saklad5’s setup, and not necessarily something we can fix.

**Comment by Saklad5** [comment] 2016-11-19 18:24
Hmm. I already pulled fresh versions of Homebrew and Homebrew-Cask, so it can’t be that on my end. I’ll try disabling config options like `.curlrc` one-by-one and see if I can find a culprit.

**Comment by vitorgalvao** [comment] 2016-11-19 18:24
Closed by mistake.

**Comment by Saklad5** [comment] 2016-11-29 15:07
Is it possible that this is a permissions bug on my end? I just solved a problem where bash couldn’t be found by fixing permissions, so that may have been causing this. I’m loathe to retry this, though, because I’d have to remove my manually installed copy of LogMeIn Hamachi. If anyone thinks that is plausible, though, I’d be happy to do so.

By the way, does `brew cask doctor` check for permissions?

**Comment by adidalal** [comment] 2016-11-29 15:29
Don't think it does, but not a bad idea

**Comment by vitorgalvao** [comment] 2016-11-29 18:10
No one else was able to reproduce this, so I’ll close it.

**Closed by vitorgalvao** 2016-11-29 18:10 UTC
Labels: awaiting maintainer feedback, cask
