### ISSUE TITLE
jetbrains EAP downloads fail with a 403

### ISSUE THREAD

**Issue by NorthIsUp** [caskroom/homebrew-cask#16444] opened 2016-01-07 00:25 UTC
It seems you need to be logged in to download EAP versions of intellij, pycharm, etc.

```
$ brew cask install intellij-idea-eap
==> Downloading https://download.jetbrains.com/idea/ideaIU-142.4465.2-custom-jdk-bundled.dmg
######################################################################## 100.0%
curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'intellij-idea-eap' with message: Download failed: https://download.jetbrains.com/idea/ideaIU-142.4465.2-custom-jdk-bundled.dmg
```

**Comment by vitorgalvao** [comment] 2016-01-07 01:34
Cask is working fine, this was either temporary or something in your setup.

Do you have a custom `.curlrc`? Because that is by far the most common cause.

**Comment by NorthIsUp** [comment] 2016-01-07 01:36
No `.curlrc` that I can find, are there any other known causes?

**Comment by vitorgalvao** [comment] 2016-01-07 01:38
Have you rechecked? Try `rm -rf "$(brew --cache)"; brew update; brew cask install intellij-idea-eap`.

**Comment by NorthIsUp** [comment] 2016-01-07 01:40
trying that now, but the vanilla curl command isn't working for me either.

```
curl -Lv -O https://download.jetbrains.com/idea/ideaIU-142.4465.2-custom-jdk-bundled.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 54.225.64.222...
* Connected to download.jetbrains.com (54.225.64.222) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
* Server certificate: download.jetbrains.com
* Server certificate: thawte EV SSL CA - G3
* Server certificate: thawte Primary Root CA
> GET /idea/ideaIU-142.4465.2-custom-jdk-bundled.dmg HTTP/1.1
> Host: download.jetbrains.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 302 Moved Temporarily
< Server: nginx
< Date: Thu, 07 Jan 2016 01:37:31 GMT
< Content-Type: text/html
< Content-Length: 154
< Connection: keep-alive
< Location: https://d1opms6zj7jotq.cloudfront.net/idea/ideaIU-142.4465.2-custom-jdk-bundled.dmg
<
* Ignoring the response-body
{ [154 bytes data]
100   154  100   154    0     0    313      0 --:--:-- --:--:-- --:--:--   313
* Connection #0 to host download.jetbrains.com left intact
* Issue another request to this URL: 'https://d1opms6zj7jotq.cloudfront.net/idea/ideaIU-142.4465.2-custom-jdk-bundled.dmg'
*   Trying 205.251.203.145...
* Connected to d1opms6zj7jotq.cloudfront.net (205.251.203.145) port 443 (#1)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.cloudfront.net
* Server certificate: Symantec Class 3 Secure Server CA - G4
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
> GET /idea/ideaIU-142.4465.2-custom-jdk-bundled.dmg HTTP/1.1
> Host: d1opms6zj7jotq.cloudfront.net
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< Date: Thu, 07 Jan 2016 01:37:31 GMT
< Server: AmazonS3
< X-Cache: Error from cloudfront
< Via: 1.1 a88de2be371f2603ffe3f00c013af6c4.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: k7_5Dg8ni4WY5nvLYxU86kWozIwkEBqxkxe56kftWtNahkjBjcEvhA==
<
{ [249 bytes data]
100   243    0   243    0     0    184      0 --:--:--  0:00:01 --:--:--   184
* Connection #1 to host d1opms6zj7jotq.cloudfront.net left intact
```

**Comment by NorthIsUp** [comment] 2016-01-07 01:40
blowing away cache has the same 403 result.

**Comment by NorthIsUp** [comment] 2016-01-07 01:42
just for fun with wget

```
wget https://download.jetbrains.com/idea/ideaIU-142.4465.2-custom-jdk-bundled.dmg
--2016-01-06 17:42:00--  https://download.jetbrains.com/idea/ideaIU-142.4465.2-custom-jdk-bundled.dmg
Resolving download.jetbrains.com (download.jetbrains.com)... 54.225.64.222
Connecting to download.jetbrains.com (download.jetbrains.com)|54.225.64.222|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://d1opms6zj7jotq.cloudfront.net/idea/ideaIU-142.4465.2-custom-jdk-bundled.dmg [following]
--2016-01-06 17:42:00--  https://d1opms6zj7jotq.cloudfront.net/idea/ideaIU-142.4465.2-custom-jdk-bundled.dmg
Resolving d1opms6zj7jotq.cloudfront.net (d1opms6zj7jotq.cloudfront.net)... 205.251.203.232, 205.251.203.141, 205.251.203.111, ...
Connecting to d1opms6zj7jotq.cloudfront.net (d1opms6zj7jotq.cloudfront.net)|205.251.203.232|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-01-06 17:42:02 ERROR 403: Forbidden.
```

**Comment by vitorgalvao** [comment] 2016-01-07 01:48
Reopening in case some other maintainer can reproduce (I’m currently taking care of updating a bunch of casks, so can’t give this my full attention), but it is extremely likely it is only on your end.

**Comment by NorthIsUp** [comment] 2016-01-07 01:52
I was unable to reproduce this issue on a clean install of OS X, so it looks like this is a local issue.

**Comment by adityadalal924** [comment] 2016-01-07 04:03
I can successfully `curl` and `wget` the url, for what it's worth.

**Comment by adityadalal924** [comment] 2016-01-07 04:12
@NorthIsUp closing the issue as it seems like you have gotten everything working. Let us know if that is not the case.

**Closed by adityadalal924** 2016-01-07 04:12 UTC
Labels: awaiting maintainer feedback
