### ISSUE TITLE
Slack contains quarantine xattrs

### ISSUE THREAD

**Issue by leetrout** [caskroom/homebrew-cask#17540] opened 2016-01-28 13:39 UTC
I had the "are you sure you want to open this" dialog every time I opened Slack after installing with cask.

Every file was marked. One random example `/opt/homebrew-cask/Caskroom/slack/1.1.10/Slack.app/Contents/Resources/AccountsController.nib: com.apple.quarantine: 0001;5697ed13;Google\x20Chrome.app;1AACA75B-42C4-4F4D-80E9-F284545AFE76`

The command to fix it is `xattr -dr com.apple.quarantine /opt/homebrew-cask/Caskroom/slack/*`

Is this expected behavior for Slack and potentially other apps or a side effect of something else? Seems odd to say it was downloaded with Chrome.

Sorry for the noise if this is expected I just hadn't seen this before with other apps (e.g. atom).

**Comment by vitorgalvao** [comment] 2016-01-28 14:35
That attribute needs to be set by someone. Chrome and Safari set it when they download files, for example, but `curl` does not. Also, at best it would be set on the zip, not the actual app, which means that flag seems to be set by the slack team itself (for whatever reason) or somewhere along the build process. We certainly don’t set it.

But you getting it every time is indeed weird. I just tried it on a clean VM and only got it once.

**Comment by adidalal** [comment] 2016-02-01 19:15
Cannot reproduce at all, unfortunately.

**Comment by leetrout** [comment] 2016-02-02 14:01
OK, thanks for double checking!

**Comment by vitorgalvao** [comment] 2016-02-03 11:53
I only got the warning once, @adidalal can’t reproduce at all, and you (@leetrout) already solved the issue. With that in mind, will be closing for now. If there are reports of this later, we’ll revisit. Slack is popular, so if this is indeed an issue, it’ll resurface.

**Closed by vitorgalvao** 2016-02-03 11:53 UTC
Labels: bug, cask
