### ISSUE TITLE
Bug report: undefined method `keys' while brew cask uninstall real-vnc

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#30633] opened 2017-03-06 14:32 UTC
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue

[insert a detailed description of your issue here]

<details><summary>Output of `brew cask uninstall real-vnc --verbose`</summary>

```
$ brew cask uninstall real-vnc --verbose
==> Running uninstall process for real-vnc; your password may be necessary
==> Removing launchctl service com.realvnc.vncserver
==> Removing launchctl service com.realvnc.vncserver.peruser
Error: undefined method `keys' for #<Array:0x007f866fab5bd8>
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/base.rb:46:in `read_script_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:207:in `uninstall_script'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:80:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:77:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:77:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:76:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:76:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:331:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:328:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:328:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:313:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:112:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit

```
</details>

<details><summary>Output of `brew doctor`</summary>

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.10-485-g29f431e85
caskroom/homebrew-cask (git revision 6b4238; last commit 2017-03-06)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (7 files, 257.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3585 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (43 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (7 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1111 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (171 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="uk_UA.UTF-8"
PATH="~/Gentoo/usr/bin:~/Gentoo/bin:~/Gentoo/tmp/usr/bin:~/Gentoo/tmp/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/sbin:~/.rvm/bin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:~/.rvm/bin:~/go/bin:/ndk-bundle:~/.node_modules/bin:~/Library/Android/sdk/ndk-bundle:/usr/local/opt/jboss-as/libexec/bin:~/bin/depot-tools:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-aliases/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dev-tools/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-portable/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```
</details>

**Comment by miccal** [comment] 2017-03-06 23:33
Cannot reproduce:
```
-bash-4.4.12- /Users/miccal [> brew cask install real-vnc
==> Downloading https://www.realvnc.com/download/file/vnc.files/VNC-6.0.2-MacOSX-x86_64.pkg
Already downloaded: /Users/miccal/Library/Caches/Homebrew/Cask/real-vnc--6.0.2.pkg
==> Verifying checksum for Cask real-vnc
==> Running installer for real-vnc; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is VNC®
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  real-vnc was successfully installed!
-bash-4.4.12- /Users/miccal [> brew cask zap real-vnc --verbose
==> Implied "brew cask uninstall real-vnc"
==> Running uninstall process for real-vnc; your password may be necessary
==> Removing launchctl service com.realvnc.vncserver
==> Removing launchctl service com.realvnc.vncserver.peruser
==> Removing files from pkgutil Bill-of-Materials
==> Dispatching zap stanza
==> Running zap process for real-vnc; your password may be necessary
==> Removing files: ["~/Library/Saved Application State/com.realvnc.vnclicensewiz.savedState", "~/Library/Saved Application State/com.realvnc.vncviewer.savedState", "~/Library/Saved Application State/com.realvnc.vncserver.savedState"]
==> Removing all staged versions of Cask 'real-vnc'
```

**Comment by miccal** [comment] 2017-03-08 02:02
I have tested this in two machines and cannot reproduce, so closing as this does not appear to be an issue with Cask.

**Closed by miccal** 2017-03-08 02:02 UTC
