### ISSUE TITLE
No such file for upgrading unity

### ISSUE THREAD

**Issue by jzw2** [caskroom/homebrew-cask#42792] opened 2018-01-14 00:12 UTC
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Doing ```brew cask upgrade unity```  gave me 

```
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/unity/2017.1.1f1,5d30cf096e79, /usr/local/Caskroom/unity/2017.1.1f1,5d30cf096e79.upgrading)
```

#### Output of your command with `--verbose --debug`

```
==> Upgrading 1 outdated package, with result:
unity 2017.3.0f3,a9f86dcd79df
==> Started upgrade process for Cask unity
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://netstorage.unity3d.com/unity/a9f86dcd79df/MacEditorInstaller/Unity.pkg
Already downloaded: /Users/johnwang/Library/Caches/Homebrew/Cask/unity--2017.3.0f3,a9f86dcd79df.pkg
==> Downloaded to -> /Users/johnwang/Library/Caches/Homebrew/Cask/unity--2017.3.0f3,a9f86dcd79df.pkg
==> Verifying download
==> Determining which verifications to run for Cask unity
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask unity
==> SHA256 checksums match
==> Starting upgrade for Cask unity
==> Un-installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x0000010215dd78>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for unity; your password may be necessary
==> Quitting application ID com.unity3d.UnityEditor5.x
==> Executing: ["/bin/launchctl", "list"]
==> Uninstalling packages:
==> Executing: ["/usr/sbin/pkgutil", "--pkgs=com.unity3d.UnityEditor5.x"]
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/unity/2017.1.1f1,5d30cf096e79, /usr/local/Caskroom/unity/2017.1.1f1,5d30cf096e79.upgrading)
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:367:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:367:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:367:in `backup'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:363:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:59:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Johns-MacBook-Pro:Project Euler johnwang$
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.4.3-39-g9a82eb6
caskroom/homebrew-cask (git revision 7d8ef; last commit 2018-01-14)
==> macOS
10.13.2
==> Java
1.8.0_25
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 745.7MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3900 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment] 2018-01-14 00:16
Please post the output of `du -hd3 /usr/local/Caskroom/unity`

**Comment by jzw2** [comment] 2018-01-14 00:19
Output of `du -hd3 /usr/local/Caskroom/unity`

```
855M	/usr/local/Caskroom/unity/2017.1.1f1,5d30cf096e79.upgrading
4.0K	/usr/local/Caskroom/unity/.metadata/2017.1.1f1,5d30cf096e79.upgrading/20171007162123.934
4.0K	/usr/local/Caskroom/unity/.metadata/2017.1.1f1,5d30cf096e79.upgrading
4.0K	/usr/local/Caskroom/unity/.metadata
855M	/usr/local/Caskroom/unity
```

**Comment by commitay** [comment] 2018-01-14 00:25
`brew cask uninstall --force unity && brew cask install unity`

**Comment by jzw2** [comment] 2018-01-14 00:28
It worked!

**Comment by commitay** [comment] 2018-01-14 00:36
I think this is the first report we've had of an upgrade error occurring in a users `/Caskroom`. 

Closing as the issue is resolved but I'll take a further look at this.

**Closed by commitay** 2018-01-14 00:36 UTC
Labels: awaiting user reply
