### ISSUE TITLE
brew cask style error

### ISSUE THREAD

**Issue by brianmorton** [caskroom/homebrew-cask#43898] opened 2018-02-12 18:31 UTC
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Issue discovered while trying to run @vitorgalvao's `cask-repair` (getting red dot error outputs).

#### Output of your command with `--verbose --debug`

```
$ brew cask style --verbose --debug
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- parser (LoadError)
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.52.1/lib/rubocop.rb:3:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-0.52.1/bin/rubocop:6:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin/rubocop:22:in `load'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin/rubocop:22:in `<main>'
Error: style check failed
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/style.rb:15:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.5.4-12-ge904983
caskroom/homebrew-cask (git revision 87e5af; last commit 2018-02-12)
==> macOS
10.13.2
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3913 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (141 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1159 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (173 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (10 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

What is interesting is that after I started experiencing this issue I tried to `brew rm ruby@2.3` (which is what I had installed) and `brew install ruby` which got me to ruby 2.5. However the `$LOAD_PATH` in homebrew still has a bunch of 2.3.3 paths...

```
$ which ruby
/usr/local/Cellar/ruby/2.5.0/bin/ruby

$ which gem
/usr/local/Cellar/ruby/2.5.0/bin/gem

$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

$ ruby env
Traceback (most recent call last):
ruby: No such file or directory -- env (LoadError)
```

When I previously had a problem with `cask-repair` there was `gem` command for removing `rubocop` and `rubocop-cask` which I tried again, but they were already removed and the gems were gone from `~/.gem` and the subdirs. It was after this that I tried to upgrade ruby.

Help appreciated in getting `brew cask style` (and by extension `cask-repair`) working again!

**Comment by brianmorton** [comment] 2018-02-12 19:40
This ended up being a bit of a problem... I removed my ruby installs (except system) and installed `rbenv` and ruby 2.5.0.

After a bit of tinkering with `brew config` and looking through some of the source files, I found that renaming 
```
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/
```
to
```
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0-old
```

and then running `brew cask style` again fixed everything:

```
$ brew cask style
==> Installing or updating 'rubocop-cask' gem
Fetching: public_suffix-3.0.2.gem (100%)
Successfully installed public_suffix-3.0.2
Fetching: parallel-1.12.1.gem (100%)
Successfully installed parallel-1.12.1
Fetching: ast-2.4.0.gem (100%)
Successfully installed ast-2.4.0
Fetching: parser-2.4.0.2.gem (100%)
Successfully installed parser-2.4.0.2
Fetching: powerpack-0.1.1.gem (100%)
Successfully installed powerpack-0.1.1
Fetching: rainbow-3.0.0.gem (100%)
Successfully installed rainbow-3.0.0
Fetching: ruby-progressbar-1.9.0.gem (100%)
Successfully installed ruby-progressbar-1.9.0
Fetching: unicode-display_width-1.3.0.gem (100%)
Successfully installed unicode-display_width-1.3.0
Fetching: rubocop-0.52.1.gem (100%)
Successfully installed rubocop-0.52.1
Fetching: rubocop-cask-0.16.0.gem (100%)
Successfully installed rubocop-cask-0.16.0
10 gems installed

0 files inspected, no offenses detected
```

This seems to have recreated the original 2.3.0 directory at the above path... so I just removed the 2.3.0-old directory and things seem to be going alright.

**Comment by vitorgalvao** [comment] 2018-02-12 20:13
Closing since it was solved.

**Comment by commitay** [comment] 2018-02-12 21:36
Looks like running `style` without a token doesn't check anything. Reproducible.

```
$ brew cask style

...

0 files inspected, no offenses detected
```

**Comment by brianmorton** [comment] 2018-02-12 22:01
@commitay the inferred problem being that `brew cask style` with no token/arguments should scan all casks?

The man page would back this up...

> style [--fix] [ token ... ]
> Check  the  given Casks for correct style using RuboCop Cask https://github.com/caskroom/rubocop-cask. If no tokens are given on the command line, all Casks are checked. With --fix, auto-correct any style errors if possible.

**Comment by commitay** [comment] 2018-02-12 22:07
Yeah, it was working a couple of weeks ago.

**Comment by CryoRenegade** [comment] 2018-02-13 15:30
Another error while styling.
```
Jacobs-MacBook-Air:homebrew-versions jacobledbetter$ brew cask style Casks/jgrasp-beta.rb [--fix]
Error: Cask 'jgrasp-beta' is unavailable: No Cask with this name exists. Did you mean “jgrasp-beta”?
```
IDK what is causing this ATM.

**Comment by gtmgianni** [comment] 2018-02-14 12:48
@CryoRenegade I believe you're getting this error because there is no cask named `jgrasp-beta` in the official `homebrew-versions` repository, hence the error message `No Cask with this name exists.`
However, if you have created a cask named `jgrasp-beta` locally, then there's probably something wrong with one of the stanzas in the cask file you've created, not with the `brew cask style` command.

Just so you know @commitay, I can reproduce your issue with running `brew cask style` with no tokens, and it not checking any casks.

**Comment by reitermarkus** [comment] 2018-02-15 08:12
> Looks like running `style` without a token doesn't check anything. Reproducible.

Works for me:

```
5406 files inspected, 5 offenses detected
```

**Comment by commitay** [comment] 2018-02-15 08:30
Clean VM, new install of Homebrew on master:

```
$ brew cask style
==> Installing or updating 'rubocop-cask' gem
Fetching: public_suffix-3.0.2.gem (100%)
Successfully installed public_suffix-3.0.2
Fetching: parallel-1.12.1.gem (100%)
Successfully installed parallel-1.12.1
Fetching: ast-2.4.0.gem (100%)
Successfully installed ast-2.4.0
Fetching: parser-2.4.0.2.gem (100%)
Successfully installed parser-2.4.0.2
Fetching: powerpack-0.1.1.gem (100%)
Successfully installed powerpack-0.1.1
Fetching: rainbow-3.0.0.gem (100%)
Successfully installed rainbow-3.0.0
Fetching: ruby-progressbar-1.9.0.gem (100%)
Successfully installed ruby-progressbar-1.9.0
Fetching: unicode-display_width-1.3.0.gem (100%)
Successfully installed unicode-display_width-1.3.0
Fetching: rubocop-0.52.1.gem (100%)
Successfully installed rubocop-0.52.1
Fetching: rubocop-cask-0.16.0.gem (100%)
Successfully installed rubocop-cask-0.16.0
10 gems installed

0 files inspected, no offenses detected
```

@reitermarkus Do you have another `rubocop-cask` in your PATH?

**Comment by vitorgalvao** [comment] 2018-02-15 11:31
Tried this on my own machine and on a VM.

VM:

```
$ brew cask --version 
Homebrew-Cask 1.5.4
caskroom/homebrew-cask (git revision c959c; last commit 2018-02-15)

$ brew cask style
0 files inspected, no offenses detected
```

non-VM:

```
$ brew cask --version
Homebrew-Cask 1.5.4-40-g988e805
caskroom/homebrew-cask (git revision c959c; last commit 2018-02-15)

$ brew cask style
5398 files inspected, no offenses detected
```

**Comment by abdelrahmanrifai** [comment] 2018-02-17 11:27
I've a similar issue running `brew cask style` produce the following error:
```
==> Installing or updating 'rubocop-cask' gem
Error: Unable to resolve dependency: user requested 'did_you_mean (= 1.0.0)'
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:231:in `search_for'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:283:in `block in sort_dependencies'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:277:in `each'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:277:in `sort_by'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:277:in `with_index'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:277:in `sort_dependencies'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:165:in `initial_state'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:106:in `start_resolution'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:64:in `resolve'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:188:in `resolve'
/Library/Ruby/Site/2.3.0/rubygems/request_set.rb:385:in `resolve'
/Library/Ruby/Site/2.3.0/rubygems/request_set.rb:397:in `resolve_current'
/Library/Ruby/Site/2.3.0/rubygems.rb:245:in `finish_resolve'
/Library/Ruby/Site/2.3.0/rubygems/rdoc.rb:15:in `<top (required)>'
/Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Library/Ruby/Site/2.3.0/rubygems/commands/install_command.rb:280:in `load_hooks'
/Library/Ruby/Site/2.3.0/rubygems/commands/install_command.rb:156:in `execute'
/usr/local/Homebrew/Library/Homebrew/utils.rb:227:in `install_gem_setup_path!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/style.rb:21:in `block in install_rubocop'
/usr/local/Homebrew/Library/Homebrew/utils.rb:400:in `capture_stderr'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/style.rb:19:in `install_rubocop'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/style.rb:11:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by MindTooth** [comment] 2018-02-20 22:07
I seem to solved mine doing:
>gem uninstall -i /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0 rubocop-cask

or

>gem uninstall -i /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0 rubocop

or (fish-shell way)

> set -x GEM_PATH /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0


Either way, I managed to make mine working again.  Needed to solve this so I could run `cask-repair`.

**Comment by abdelrahmanrifai** [comment] 2018-02-20 23:56
Well, I found that don't have a `bundle` folder into this path `/usr/local/Homebrew/Library/Homebrew/vendor`.

Doing some researching and reading through those issues https://github.com/Homebrew/brew/issues/3760, https://github.com/Homebrew/brew/pull/3781, https://github.com/Homebrew/brew/pull/3736.

I decided to go back to this version of [utils.rb](https://github.com/MikeMcQuaid/brew/blob/459b113e28cab57cde94625b3f284e54986c2167/Library/Homebrew/utils.rb) file, right before those changes to `ENV["GEM_HOME"]`, `ENV["GEM_PATH"`, and everything worked fine for me!

However running `brew cask style` installed `rubocop ` and `rubocop-cask` to the system `/usr/bin/gem` not the one installed via brew `/usr/local/bin/gem`.

```
$ which -a gem
/usr/local/bin/gem
/usr/bin/gem

$ gem --version
2.7.6

$ /usr/local/bin/gem --version
2.7.6

$ /usr/bin/gem  --version
2.7.2
```

I don't know much about ruby/gem, however I tried to add helpful info as much as I can.

Mentioning @MikeMcQuaid since he is the owner of those commits.

**Comment by commitay** [comment] 2018-02-21 02:02
> However running `brew cask style` installed `rubocop ` and `rubocop-cask` to the system `/usr/bin/gem` not the one installed via brew `/usr/local/bin/gem`.

Homebrew uses system ruby or its own portable ruby if system ruby is to old.

> I decided to go back to this version of [utils.rb](https://github.com/MikeMcQuaid/brew/blob/459b113e28cab57cde94625b3f284e54986c2167/Library/Homebrew/utils.rb) file

I'd recommend not doing this.

> Well, I found that don't have a `bundle` folder into this path `/usr/local/Homebrew/Library/Homebrew/vendor`.

@abdelrahmanrifai Please open a new issue for this.

**Comment by commitay** [comment] 2018-02-21 02:05
Closing as the original user issue was resolved.

`style` without tokens not working moved to https://github.com/caskroom/homebrew-cask/issues/44190

**Closed by commitay** 2018-02-21 02:05 UTC
Labels: awaiting maintainer feedback, bug, core
