### ISSUE TITLE
“Updated Formulae” message lies

### ISSUE THREAD

**Issue by anbotero** [caskroom/homebrew-cask#10047] opened 2015-03-14 20:10 UTC
It’s happened to me twice already, or at least that I’ve noticed.

I run `brew cask update` and the list of _Updated Formulae_ output doesn’t include formulae that have indeed been updated.

It displays some, but not all of them. Today I updated them, and it didn’t display `flash`, which I just checked because the Operating System itself suggested me to upgrade it.

I’m not sure if it’s been fortuitous or not, but today with the `flash` cask I had proof it is indeed happening.

**Comment by vitorgalvao** [comment] 2015-03-14 20:37
`brew cask update` is just an alias for `brew update`, it doesn’t do anything special, so the issue is likely not on our side.

This is also a duplicate of #5839.

**Closed by vitorgalvao** 2015-03-14 20:37 UTC
