### ISSUE TITLE
Can't install minikube

### ISSUE THREAD

**Issue by lalib** [caskroom/homebrew-cask#40149] opened 2017-10-29 20:55 UTC
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I can not install minikube (https://github.com/caskroom/homebrew-cask/blob/master/Casks/minikube.rb)

#### Output of your command with `--verbose --debug`

```
$ brew cask install minikube --verbose --debug
==> Determining which containers to use based on 'container :type'
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb
All Formula dependencies satisfied.
==> Downloading
==> Downloading https://storage.googleapis.com/minikube/releases/v0.23.0/minikube-darwin-amd64
Already downloaded: /Users/balp/Library/Caches/Homebrew/Cask/minikube--0.23.0
==> Downloaded to -> /Users/balp/Library/Caches/Homebrew/Cask/minikube--0.23.0
==> Verifying download
==> Determining which verifications to run for Cask minikube
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask minikube
==> SHA256 checksums match
==> Installing Cask minikube
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on 'container :type'
==> Using container class Hbc::Container::Naked for /Users/balp/Library/Caches/Homebrew/Cask/minikube--0.23.0
==> Executing: ["/usr/bin/ditto", "--", "/Users/balp/Library/Caches/Homebrew/Cask/minikube--0.23.0", "/usr/local/Caskroom/minikube/0.23.0/minikube-darwin-amd64"]
==> Creating metadata directory /usr/local/Caskroom/minikube/.metadata/0.23.0/20171029205420.969.
==> Creating metadata subdirectory /usr/local/Caskroom/minikube/.metadata/0.23.0/20171029205420.969/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x000001013e3df0>
==> Installing artifact of class Hbc::Artifact::Binary
==> Linking Binary 'minikube-darwin-amd64' to '/usr/local/bin/minikube'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/minikube/0.23.0/minikube-darwin-amd64", "/usr/local/bin/minikube"]
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
==> Executing: ["/usr/bin/xattr", "-p", "com.apple.metadata:kMDItemAlternateNames", "/usr/local/Caskroom/minikube/0.23.0/minikube-darwin-amd64"]
==> Existing metadata is: ''
==> Executing: ["/bin/chmod", "--", "u+rw", "/usr/local/Caskroom/minikube/0.23.0/minikube-darwin-amd64", "/usr/local/Caskroom/minikube/0.23.0/minikube-darwin-amd64"]
==> Executing: ["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "(\"minikube\")", "/usr/local/Caskroom/minikube/0.23.0/minikube-darwin-amd64"]
==> Purging files for version 0.23.0 of Cask minikube
Error: Command failed to execute!

==> Failed command:
/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames ("minikube") /usr/local/Caskroom/minikube/0.23.0/minikube-darwin-amd64

==> Standard Output of failed command:


==> Standard Error of failed command:
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources


==> Exit status of failed command:
#<Process::Status: pid 24314 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:76:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:70:in `add_altname_metadata'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:60:in `create_filesystem_link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:48:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:7:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.6-142-g4c44266
caskroom/homebrew-cask (git revision a3adc2; last commit 2017-10-29)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 39.3MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3780 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (174 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="~/.jenv/bin:~/.jenv/shims:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```
#### Output of `brew config`

```
$ brew config
HOMEBREW_VERSION: 1.3.6-142-g4c44266
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4c44266aa5cfab215b92ef0aa5bb12112d8a4cb8
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d3a093ec1e3360de9b663f454ab27dede8d46231
Core tap last commit: 30 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: 9, 1.8.0_151, 1.8.0_144, 1.8.0_141, 1.8.0_131
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 9.0.1.0.1.1506734476
X11: N/A
```

#### Output of `brew doctor`

```
$ brew doctor                       
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/LibSideSyncOSX9.dylib
  /usr/local/lib/ss_conn_lib.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker-machine
  python3
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.6-142-g4c44266
caskroom/homebrew-cask (git revision a3adc2; last commit 2017-10-29)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 39.3MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3780 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (174 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="~/.jenv/bin:~/.jenv/shims:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment] 2017-10-29 21:09
Please post the output of `brew config`

**Comment by lalib** [comment] 2017-10-29 21:18
@commitay I have added into original post.

**Comment by commitay** [comment] 2017-10-29 21:22
Please post `brew doctor`

**Comment by lalib** [comment] 2017-10-29 21:26
@commitay added `brew doctor` and `brew cask doctor`

**Comment by commitay** [comment] 2017-10-29 21:47
I can't reproduce this error. 
```
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```
It's a python issue that I think is caused by:
```
Warning: Python is installed at /Library/Frameworks/Python.framework
```

**Comment by lalib** [comment] 2017-10-29 22:24
@commitay any ideas about how to fix it?

**Comment by commitay** [comment] 2017-10-30 04:22
Not really, but I'd try removing all non Homebrew pythons. 

A quick google search also suggests that updating pip / pip3 packages may help.

**Comment by lalib** [comment] 2017-10-30 22:16
@commitay I tried a lot of things such as removing pythons which are not managed by Homebrew, upgrading pip/pip3 packages etc. The result is the same.

#### Output of  `brew doctor`

```
$ brew doctor                       
Your system is ready to brew.
```

**Comment by commitay** [comment] 2017-10-30 23:55
The python frameworks are still in your PATH.

**Comment by lalib** [comment] 2017-10-31 09:05
@commitay sorry i forgot to clean it.

#### Output of `brew doctor`

```
$ brew doctor                       
Your system is ready to brew.
```

### Output of `brew cask doctor`

```
$brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.6-142-g4c44266
caskroom/homebrew-cask (git revision a6d55; last commit 2017-10-31)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (6 files, 273.4MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3782 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (174 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="~/.jenv/bin:~/.jenv/shims:~/.jenv/bin:~/.jenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

Anything else i should check?

**Comment by commitay** [comment] 2017-10-31 09:37
Try running this and post the output.
```
touch test.txt && xattr -w test "this is a test" test.txt && xattr -l test.txt
```

**Comment by lalib** [comment] 2017-10-31 09:44
@commitay here you go;

```
$ touch test.txt && xattr -w test "this is a test" test.txt && xattr -l test.txt
test: this is a test
```

**Comment by commitay** [comment] 2017-10-31 10:07
Output of `which -a xattr`?

**Comment by lalib** [comment] 2017-10-31 10:42
@commitay here you go;

```
$ which -a xattr
/usr/local/bin/xattr
/usr/bin/xattr
```

**Comment by commitay** [comment] 2017-10-31 10:49
Try this again:
```
touch test.txt && /usr/bin/xattr -w test "this is a test" test.txt && /usr/bin/xattr -l test.txt
```

**Comment by lalib** [comment] 2017-10-31 10:51
@commitay here you go;

```
$ touch test.txt && /usr/bin/xattr -w test "this is a test" test.txt && /usr/bin/xattr -l test.txt
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

It seems the problem is related to  `/usr/bin/xattr` but i do not know how to disable it.

**Comment by commitay** [comment] 2017-10-31 11:34
I think the issue is that the python frameworks have somehow removed `setuptools`.

I'm not very familiar with python so I can't really suggest a "correct" way to install them.

Python forums or stackoverflow may have a way of resolving this, it isn't an issue with Homebrew-Cask.

**Closed by commitay** 2017-10-31 11:34 UTC
