### ISSUE TITLE
Bug report: brew cask install cakebrew fails with errors

### ISSUE THREAD

**Issue by edeandrea** [caskroom/homebrew-cask#26816] opened 2016-11-16 13:53 UTC
#### Description of issue

When trying to install cakebrew via the command on OSX 10.11.6

`brew cask install cakebrew`

I got the following error:

```
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3530, done.
remote: Compressing objects: 100% (3515/3515), done.
remote: Total 3530 (delta 31), reused 166 (delta 11), pack-reused 0
Receiving objects: 100% (3530/3530), 1.14 MiB | 205.00 KiB/s, done.
Resolving deltas: 100% (31/31), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/metagrowler.rb
undefined method `cask' for Formulary::FormulaNamespace0a3fc67eb7f20792f6a4ee633903a783:Module
Error: Cannot tap caskroom/cask: invalid syntax in tap!
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:226:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

I then proceeded to https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md and followed those instructions. The commands detailed there failed as well:

```
$ cd $(brew --repo); git fetch; git reset --hard origin/master
HEAD is now at edf042e Merge pull request #1522 from MikeMcQuaid/audit-one-previous-commit

$ brew untap phinze/cask; brew untap caskroom/cask; brew uninstall --force brew-cask
Error: No available tap phinze/cask.
Error: No available tap caskroom/cask.

$ brew cleanup; brew cask cleanup; brew update
Warning: Skipping cloudfoundry/tap/cf-cli: most recent version 6.22.2 not installed
Warning: Skipping git-lfs: most recent version 1.4.4 not installed
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3530, done.
remote: Compressing objects: 100% (3515/3515), done.
remote: Total 3530 (delta 31), reused 166 (delta 11), pack-reused 0
Receiving objects: 100% (3530/3530), 1.14 MiB | 718.00 KiB/s, done.
Resolving deltas: 100% (31/31), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/metagrowler.rb
undefined method `cask' for Formulary::FormulaNamespace0a3fc67eb7f20792f6a4ee633903a783:Module
Error: Cannot tap caskroom/cask: invalid syntax in tap!
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:226:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Already up-to-date.
```

So I'm now not sure what went wrong or how to fix it.

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
==> Tapping caskroom/cask
git clone https://github.com/caskroom/homebrew-cask /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask --depth=1
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3530, done.
remote: Compressing objects: 100% (3515/3515), done.
remote: Total 3530 (delta 31), reused 166 (delta 11), pack-reused 0
Receiving objects: 100% (3530/3530), 1.14 MiB | 444.00 KiB/s, done.
Resolving deltas: 100% (31/31), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/metagrowler.rb
undefined method `cask' for Formulary::FormulaNamespace0a3fc67eb7f20792f6a4ee633903a783:Module
Error: Cannot tap caskroom/cask: invalid syntax in tap!
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:226:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Your system is ready to brew.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3530, done.
remote: Compressing objects: 100% (3515/3515), done.
remote: Total 3530 (delta 31), reused 166 (delta 11), pack-reused 0
Receiving objects: 100% (3530/3530), 1.14 MiB | 175.00 KiB/s, done.
Resolving deltas: 100% (31/31), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/metagrowler.rb
undefined method `cask' for Formulary::FormulaNamespace0a3fc67eb7f20792f6a4ee633903a783:Module
Error: Cannot tap caskroom/cask: invalid syntax in tap!
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:226:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
</details>

**Comment by MikeMcQuaid** [comment] 2016-11-16 14:19
Duplicate of https://github.com/caskroom/homebrew-cask/issues/26815.

**Comment by vitorgalvao** [comment] 2016-11-16 14:22
Closed as duplicate.

**Closed** 2016-11-16 14:22 UTC
