### ISSUE TITLE
Uninstallation of graphviz fails

### ISSUE THREAD

**Issue by adius** [caskroom/homebrew-cask#12820] opened 2015-07-25 18:19 UTC
```
brew cask uninstall graphviz
==> Running uninstall process for graphviz; your password may be necessary
==> Removing files from pkgutil Bill-of-Materials
==> rmdir: /usr/local/include/graphviz: Not a directory
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/bin/rmdir", "--", "#<Pathname:/usr/local/include/graphviz>"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 70281 exit 1>
```

**Comment by vitorgalvao** [comment] 2015-07-27 19:31
Can’t reproduce (using a clean VM). Can any @caskroom/maintainers?

**Comment by phinze** [comment] 2015-07-27 19:44
Could not reproduce locally either. @adius does that dir have any files in it on your machine?

**Comment by Ngrd** [comment] 2015-07-27 19:56
Also can't reproduce. Uninstallation process works fine for me.

**Comment by adius** [comment] 2015-07-27 21:04
@phinze The directory is empty … if it even is one:

```sh
adrians-mac:~$ file /usr/local/include/graphviz
/usr/local/include/graphviz: directory
adrians-mac:~$ rmdir /usr/local/include/graphviz
rmdir: /usr/local/include/graphviz: Not a directory
```

wtf? =D

**Comment by vitorgalvao** [comment] 2015-07-31 11:47
Seems like an error in your configuration, then, and seeing as we can’t reproduce, we can’t help with a fix. Closing.

**Closed by vitorgalvao** 2015-07-31 11:47 UTC
Labels: bug, cask, waiting-maintainer-feedback

**Comment by adius** [comment] 2015-07-31 15:51
Yeah, no idea what was wrong. I just deleted `/usr/local/include/graphviz ` and then I was able to run uninstall.
