### ISSUE TITLE
Bug report: Can not uninstall xquartz

### ISSUE THREAD

**Issue by heyarne** [caskroom/homebrew-cask#26551] opened 2016-11-07 15:39 UTC
#### Description of issue

After installing `xquartz`, I can not `brew cask rm` it.

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
$ brew cask rm xquartz --verbose
==> Running uninstall process for xquartz; your password may be necessary
==> Removing launchctl service org.macosforge.xquartz.startx
Password:
==> Quitting application ID org.macosforge.xquartz.X11
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/bin/osascript -e tell application \"System Events\" to count processes whose bundle identifier is \"org.macosforge.xquartz.X11\"

==> Standard Output of failed command:


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 1948 exit 133>
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php54

Warning: Your Xcode (8.0) is outdated.
Please update to Xcode 8.1 (or delete it).
Xcode can be updated from the App Store.


Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  homebrew/science/opencv3
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
$ brew cask doctor
==> macOS Release:
10.11.6
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.0
Homebrew/homebrew-core (git revision f9c81; last commit 2016-11-07)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.0
caskroom/homebrew-cask (git revision fbcf3; last commit 2016-11-07)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/arnold/Library/Caches/Homebrew/Cask
0 files, 0B
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions
==> Homebrew-Cask Default Tap Cask Count:
3432
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/usr/local/sbin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
LANGUAGE="en_UTF.UTF-8?"
LC_ALL="en_US.UTF-8"
LC_CTYPE="UTF-8"
==> Running As Privileged User:
No
```
</details>

#### Additional information

```
$ brew cask info xquartz
xquartz: 2.7.11
https://www.xquartz.org/
/usr/local/Caskroom/xquartz/2.7.11 (74.6M)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/xquartz.rb
==> Name
XQuartz
==> Artifacts
XQuartz.pkg (pkg)
```

**Comment by miccal** [comment] 2016-11-07 21:44
You need to `brew cask uninstall xquartz` or `brew cask zap xquartz`.

**Comment by heyarne** [comment] 2016-11-08 11:55
Are `rm` and `uninstall` not synonymous?
```
$ brew cask uninstall xquartz --force
==> Running uninstall process for xquartz; your password may be necessary
==> Removing launchctl service org.macosforge.xquartz.startx
Password:
==> Quitting application ID org.macosforge.xquartz.X11
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/bin/osascript -e tell application \"System Events\" to count processes whose bundle identifier is \"org.macosforge.xquartz.X11\"

==> Standard Output of failed command:


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 13134 exit 133>
```
The same script fails when `zap`ing.

**Comment by miccal** [comment] 2016-11-08 12:30
For my installation of Xquartz I have the following two files:
```
/Library/LaunchAgents/org.macosforge.xquartz.startx.plist
/Library/LaunchDaemons/org.macosforge.xquartz.privileged_startx.plist
```

I notice in the [Cask file](https://github.com/caskroom/homebrew-cask/blob/master/Casks/xquartz.rb) under `launchctl:` it lists the first file, but the second is not mentioned anywhere.

I am not sure if this has something do do with the problem?

**Comment by reitermarkus** [comment] 2016-11-08 23:11
> Are `rm` and `uninstall` not synonymous?

Yes, they are, so this can't be the problem.

Does running 

```
/usr/bin/sudo -E -- /usr/bin/osascript -e "tell application \"System Events\" to count processes whose bundle identifier is \"org.macosforge.xquartz.X11\""
```

by itself also fail?

**Comment by heyarne** [comment] 2016-11-09 06:51
No, running the command by itself does no throw any error.

**Comment by dcondrey** [comment] 2016-11-25 22:06
I was not able to reproduce this but perhaps this can be resolved by removing `quit` and/or using a uninstall preflight system_command which will run as sudo by default.

    uninstall quit:      'org.macosforge.xquartz.X11',
            launchctl: 'org.macosforge.xquartz.startx',
            pkgutil:   'org.macosforge.xquartz.pkg',
            delete:    '/opt/X11/'

---

    uninstall_preflight do
        system_command '/bin/launchctl', args: ['unload', '/Library/LaunchAgents/org.macosforge.xquartz.startx.plist']
        
        system_command '/bin/launchctl', args: ['unload', '/Library/LaunchDaemons/org.macosforge.xquartz.privileged_startx.plist']

        system_command 'rm', args: ['-rf', '/opt/X11* /Library/Launch*/org.macosforge.xquartz.* /Applications/Utilities/XQuartz.app /etc/*paths.d/*XQuartz']
    end

    uninstall pkgutil: 'org.macosforge.xquartz.pkg'

**Closed** 2016-12-08 19:00 UTC
Labels: cask
