### ISSUE TITLE
Reconsider default installation path

### ISSUE THREAD

**Issue by ndr-qef** [caskroom/homebrew-cask#2534] opened 2014-01-21 22:44 UTC
I would like to propose /Applications as the default installation path, changing from the current ~/Applications. For past opinions surrounding this issue, see #30.

To better direct the discussion, note that I am not arguing that installing to /Applications is strictly better practice than installing to ~/Applications. My suggestion is that symlinking apps to /Applications would be a better default, as it is where most users expect to find their apps based on common practice. Consider the following:

- As of 10.7, OSX does not create ~/Applications. A user application folder is supported, but optional. On 10.6, the user application folder was created empty. See [thread on Apple Support](https://discussions.apple.com/message/16752624#16752624).

- The Mac App Store installs to /Applications. I would expect most Cask users to have at least one MAS-only application they like or need (cue harrowing screams of those who like to automate provisioning of their machines), which is problematic for those who favor ~/Applications as some of their software will be relegated to the global folder.

- Homebrew changed the default --linkapps path to /Applications about five months ago with https://github.com/Homebrew/homebrew/pull/22378. (--linkapps symlinks certain programs, e.g. Emacs, to a folder, similarly to Cask.) Given that Cask is implemented as an external brew command, it should be desirable to mantain consistent behavior for shared functionality.

- Other applications seemingly expect the absence of a user application folder. E.g. Alfred, a very popular tool, does not include ~/Applications in its search scope.

I find these to be increasingly good reasons to adapt our current default path; the trend appears rather clear. Of course, Cask would remain configurable, and those who prefer to keep Cask application separate will be able to change their installation folder with `export HOMEBREW_CASK_OPTS`. However, most users (particularly new ones) would be better served by the more common /Applications as default.

**Comment by vitorgalvao** [comment] 2015-01-23 00:43
Ok, so here’s the “score” so far.

*/Applications:*
@ndr-qef
@vitorgalvao
@rolandwalker ([fine with the default, but uses this one](https://github.com/caskroom/homebrew-cask/issues/2534#issuecomment-32987789))
@muescha
@majjoha 
@Keithbsmiley
@hanxue
@AlJohri
@dmyers
@gossi
@StevenClontz (I think)
@lgarron ([copies things in part because the default install location breaks some apps](https://github.com/caskroom/homebrew-cask/issues/2534#issuecomment-34026701))
@wamatt (maybe, as he had the wrong idea at first and hasn’t stated if his opinion changed)

*~/Applications:*
@adamv
@leoj3n
@goxberry ([slightly](https://github.com/caskroom/homebrew-cask/issues/2534#issuecomment-32985092))

If anyone changed their opinion or I misunderstood it, please tell me so I can update the list. The results, however, are pretty obvious. I’m willing to bet most user that know about `export HOMEBREW_CASK_OPTS="--appdir=/Applications"` have it set up that way.

Making this change isn’t a big deal, as it’s easy to change it back. However, defaults do matter, and it seems we have the wrong one. Either way, we should make a decision and close this.

**Comment by Amorymeltzer** [comment] 2015-01-23 01:08
I didn't chime in above (I'm with the majority) but just as further indication outside of here, a search for "HOMEBREW_CASK_OPTS appdir" yields ~ 1000 code results; a quick scan of the first 20 pages indicates around 95+% use `/Applications`.

**Comment by StevenClontz** [comment] 2015-01-23 01:10
FWIW `~/Applications` has grown on me in the past year, but with the ability to customize I'm okay with either direction. So you could just remove me from the vote tally if it makes a difference.

**Comment by wamatt** [comment] 2015-01-23 04:21
thanks @vitorgalvao. so it's ```/Applications``` for me, in case it wasn't clear :)

> a quick scan of the first 20 pages indicates around 95+% use /Applications. - @Amorymeltzer

quite useful and compelling. ty!

**Comment by nylen** [comment] 2015-03-10 19:24
Another :+1: for `/Applications` as default.  It [looks like](https://discussions.apple.com/message/16752624#16752624) Apple is trying to phase out support for `~/Applications`, and `cask` should follow Apple's lead.

I just want all of my installed applications to show up in the *Applications* stack in the dock.  I don't care about the rest.  For now, I'm accomplishing that using the line in `.bashrc` mentioned above:

```sh
export HOMEBREW_CASK_OPTS="--appdir=/Applications"`
```

I shouldn't have to worry about things like that, **it should just work** ;)

**Comment by phinze** [comment] 2015-03-10 19:55
Thanks for all the contributions here, folks!

I think the overall opinion has fallen pretty squarely on a move to `/Applications` for the default, so I"ll close this discussion thread and we can track the actual change over at #9178. :+1:

**Closed by phinze** 2015-03-10 19:55 UTC

**Comment by lloydde** [comment] 2015-04-04 20:55
Thanks @phinze and all for this discussion and moving forward with implementing the change to /Applications folder. I think this change will really assist non-power users like myself, who spent a good 45 first trying to understand why my casks were not in Finder. It's a hard thing to search for as ~/Applications don't seem in use outside of the homebrew world.

**Comment by tjnycum** [comment] 2015-08-13 05:07
> a search for "HOMEBREW_CASK_OPTS appdir" yields ~1000 code results; a quick scan of the first 20 pages indicates around 95+% use /Applications.

Unless you excluded the instances in which --appdir was the *only* option being specified, that's neither surprising nor significant. Most people don't go to the trouble of learning about and setting an environment variable just to reinforce the default behavior.

**Comment by vitorgalvao** [comment] 2015-08-13 11:05
@tjnycum There’s also [the very small sample size in this issue](https://github.com/caskroom/homebrew-cask/issues/2534#issuecomment-71128895), and most importantly [**this was already decided on and was going to be implemented anyway**](https://github.com/caskroom/homebrew-cask/pull/9178).

> Most people don't go to the trouble of learning about and setting an environment variable just to reinforce the default behavior.

Yes, but you know what many of them did before there were that many blog posts talking abut homebrew-cask? They opened issues and talked to us asking about how to do it. Just because most people don’t do it, doesn’t mean they don’t want to. The amount of people I’ve encountered here that is afraid to even try a small cask fix because they’re afraid they’ll break something is surprising. Defaults matter.

I understand you might be disappointed by the new changes, and you seem overly worried about that, but please don’t turn this into a vendetta. I’d really hate to waste my time getting notifications of you commenting on old decided-on posts and having to explain reasonings again and again.

We’re not making changes to annoy you, but because we think they’re the best for the project and the community. We’ve been doing this for a few years now ([that doesn’t mean we have all the answers](https://en.wikipedia.org/wiki/Argument_from_authority)), we were (and are) always open to hear new ideas, and we’re willing to change how things work ([case in point](https://github.com/caskroom/homebrew-cask/issues/13201)), but we’ve seen a lot of casks and ways of handling them, and I personally do so daily and have done it since I first became a maintainer, in homebrew-cask’s infancy.

We know a thing or two about what works and doesn’t, and that gives us a lot of context about what the steps to take should be. We always take the community into account, yes, and this last change is no exception, but if you’re going to argue, please start with searching and reading old issues to try and get context beforehand. It’s the second time I have to answer you at length with things that are **explained in the post itself**, and that’s really not how I intend to spend my day.

**Comment by alexchandel** [comment] 2016-05-16 12:58
Can this happen already? It's been punted to #13201 and locked for months, and yet there's no way to change the default installation root to `/` instead of `~`, not even a good workaround until #13201 is implemented. Having to specify `--appdir=/Applications --prefpanedir=/Library/PreferencePanes --qlplugindir=/Library/QuickLook --fontdir=/Library/Fonts --input_methoddir="/Library/Input Methods" --screen_saverdir="/Library/Screen Savers"` is absolutely absurd. Why isn't there a `--rootdir=/` option?

**Comment by vitorgalvao** [comment] 2016-05-16 13:45
> Can this happen already?
> (…)
> Unbelievable.

Good news! This can happen today, and all you have to do is submit the fix yourself! No good? Well, then please do tell how much you’re contributing monetarily for a kind soul that will do it. Make it good, though, no sense is wasting people’s time with low proposals.

We do not work for you. You’re getting this software for free and without guarantees. Either help or gp away. We know this is slow in happening, and that is because we’re very low in core developers. Your complaining is contributing nothing.

Look for `HOMEBREW_CASK_OPTS` in the documentation. You do not need to specify that long command every time.

**Comment by alexchandel** [comment] 2016-05-16 14:58
@vitorgalvao I'm happy to do either. 2 questions: where do I locally edit homebrew-cask source (i.e. where's the git repo—it's not /usr/local I take it)? And where's the best place in the source to declare such a global directory root?

Alternatively, how much to donate to fix it this week?

**Comment by vitorgalvao** [comment] 2016-05-16 15:06
@alexchandel Thank you! With that, we can work.

To take a stab at it, look into [hacking.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/hacking.md) first, as it describes how to setup yourself to contribute to the core.

After that, look at https://github.com/caskroom/homebrew-cask/pull/13966 that has a bunch of work already done, but some standing issues. Like I said, a big part of the issue is our lack of core developers. That even makes it hard to do reviews. If you take issue and review it/fix the latest problems, either alone or with @mwean, we can proceed.

After that, if you’d still rather donate to have the work done, please let me know, and I’ll put out a warning on #13201 and contact the rest of @caskroom/maintainers to see what we can arrange.

**Comment by mwean** [comment] 2016-05-16 18:42
@alexchandel FWIW I'll try to take a look at my branch tonight.
