### ISSUE TITLE
Bug report: Brew Cask Search not returning results from all taps

### ISSUE THREAD

**Issue by ibrokemypie** [caskroom/homebrew-cask#27360] opened 2016-12-04 00:03 UTC
#### Description of issue

When searching for "moon", only newmoon from the main tap and palemoon from the unofficial tap are returned, although palemoon from the versions tap is still able to be installed etc. All taps are updated and on branch master.

<details><summary>Output of `brew cask search moon --verbose`</summary>

```
$ brew cask search moon --verbose
==> Partial matches
alehouse/unofficial/palemoon                                        alehouse/unofficial/palemoon                                        newmoon

```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libfluidsynth.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fluidsynth/audio.h
  /usr/local/include/fluidsynth/event.h
  /usr/local/include/fluidsynth/gen.h
  /usr/local/include/fluidsynth/log.h
  /usr/local/include/fluidsynth/midi.h
  /usr/local/include/fluidsynth/misc.h
  /usr/local/include/fluidsynth/mod.h
  /usr/local/include/fluidsynth/ramsfont.h
  /usr/local/include/fluidsynth/seq.h
  /usr/local/include/fluidsynth/seqbind.h
  /usr/local/include/fluidsynth/settings.h
  /usr/local/include/fluidsynth/sfont.h
  /usr/local/include/fluidsynth/shell.h
  /usr/local/include/fluidsynth/synth.h
  /usr/local/include/fluidsynth/types.h
  /usr/local/include/fluidsynth/version.h
  /usr/local/include/fluidsynth/voice.h
  /usr/local/include/fluidsynth.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libfluidsynth.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/fluidsynth.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libfluidsynth.a

```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.11.6
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.2-15-g52691cd
Homebrew/homebrew-core (git revision aaf2; last commit 2016-12-03)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.2-15-g52691cd
caskroom/homebrew-cask (git revision ffcc; last commit 2016-12-03)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/Conor/Library/Caches/Homebrew/Cask
0 files, 0B
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/alehouse/homebrew-unofficial
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions
/usr/local/Homebrew/Library/Taps/szhu/homebrew-personal
==> Homebrew-Cask Default Tap Cask Count:
3475
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Users/Conor/.zgen/unixorn/tumult.plugin.zsh-master/bin:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dev-tools/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_AU.UTF-8"
LC_CTYPE="en_AU.UTF-8"

```
</details>

**Comment by adidalal** [comment] 2016-12-04 00:09
Is it this bug? https://github.com/caskroom/homebrew-cask/issues/16732

**Comment by vitorgalvao** [comment] 2016-12-04 00:43
@adidalal No, because it appears the `versions` repo is tapped.

I can’t reproduce, though:

```
$ brew cask search moon
==> Partial matches
font-icomoon               newmoon                    palemoon
```

**Comment by ibrokemypie** [comment] 2016-12-04 00:49
@vitorgalvao perhaps it is because I tapped the unofficial repo? seems that palemoon is getting entirely replaced with the unofficial version ``(23/56) palemoon: 27.0.1 -> 26.3.2``

**Comment by vitorgalvao** [comment] 2016-12-04 01:05
@ibrokemypie That’s exactly it. Just remembered this: https://github.com/caskroom/homebrew-cask/pull/7906.

**Comment by vitorgalvao** [comment] 2016-12-04 01:09
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/27364.

**Closed by vitorgalvao** 2016-12-04 01:09 UTC
