### ISSUE TITLE
Bug report: Brew cask issues in Fedora 23 Linux

### ISSUE THREAD

**Issue by boarderdav** [caskroom/homebrew-cask#17530] opened 2016-01-27 23:49 UTC
### Description of issue

I've been wrestling with this issue for the last couple hours.  I've uninstalled homebrew and reinstalled it a couple times too.  I'm running newest version of Fedora 23 Linux and having trouble configuring CASK.  Here's a typical error I keep getting

I get this every time I use "cask" in a command line phrase.  I've tried the instructions as shown in the above messages and I've gone through the instructions all this github page, homebrew/linux and caskroom.io  Still can't get it working.  

Any help would be greatly appreciated. 
Thanks!

### Output of `brew cask <command> --verbose`

```
[djenkins@wag2-174-110 local]$ brew cask install google-chrome --verbose
Error: Permission denied @ dir_s_mkdir - /Library
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/share/ruby/fileutils.rb:252:in `mkdir'
/usr/share/ruby/fileutils.rb:252:in `fu_mkdir'
/usr/share/ruby/fileutils.rb:226:in `block (2 levels) in mkdir_p'
/usr/share/ruby/fileutils.rb:224:in `reverse_each'
/usr/share/ruby/fileutils.rb:224:in `block in mkdir_p'
/usr/share/ruby/fileutils.rb:210:in `each'
/usr/share/ruby/fileutils.rb:210:in `mkdir_p'
/usr/share/ruby/pathname.rb:564:in `mkpath'
/home/djenkins/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/vendor/homebrew-fork/global.rb:18:in `mkpath'
/home/djenkins/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:57:in `init'
/home/djenkins/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:115:in `process'
/home/djenkins/.linuxbrew/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/djenkins/.linuxbrew/Library/brew.rb:25:in `require?'
/home/djenkins/.linuxbrew/Library/brew.rb:91:in `<main>'
Error: Kernel.exit
```

### Output of `brew doctor`
```
[djenkins@wag2-174-110 local]$ brew doctor
Your system is ready to brew.
```

### Output of `brew cask doctor`

```
[djenkins@wag2-174-110 local]$ brew cask doctor
==> Tapping caskroom/cask
Cloning into '/home/djenkins/.linuxbrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3447, done.
remote: Compressing objects: 100% (3402/3402), done.
remote: Total 3447 (delta 65), reused 245 (delta 23), pack-reused 0
Receiving objects: 100% (3447/3447), 5.87 MiB | 11.56 MiB/s, done.
Resolving deltas: 100% (65/65), done.
Checking connectivity... done.
Tapped 1 formula (3,413 files, 13.3M)
Error: Permission denied @ dir_s_mkdir - /Library
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/share/ruby/fileutils.rb:252:in `mkdir'
/usr/share/ruby/fileutils.rb:252:in `fu_mkdir'
/usr/share/ruby/fileutils.rb:226:in `block (2 levels) in mkdir_p'
/usr/share/ruby/fileutils.rb:224:in `reverse_each'
/usr/share/ruby/fileutils.rb:224:in `block in mkdir_p'
/usr/share/ruby/fileutils.rb:210:in `each'
/usr/share/ruby/fileutils.rb:210:in `mkdir_p'
/usr/share/ruby/pathname.rb:564:in `mkpath'
/home/djenkins/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/vendor/homebrew-fork/global.rb:18:in `mkpath'
/home/djenkins/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:57:in `init'
/home/djenkins/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:115:in `process'
/home/djenkins/.linuxbrew/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/djenkins/.linuxbrew/Library/brew.rb:25:in `require?'
/home/djenkins/.linuxbrew/Library/brew.rb:91:in `<main>'
```

**Comment by tsparber** [comment] 2016-01-28 04:29
Duplicate of #16835 (see https://github.com/caskroom/homebrew-cask/issues/16835#issuecomment-170941290). `brew-cask` runs only on OS X.

**Closed** 2016-01-28 04:31 UTC

**Comment by jawshooah** [comment] 2016-01-28 04:33
@tsparber is correct, but I'm curious, since this is apparently becoming a trend: why did you expect to be able to use Homebrew-Cask on Linux? I think it's pretty clear from the readme that we are exclusively for OSX, but if that's not the case, we should make it even clearer somehow.
