### ISSUE TITLE
DiffMerge command line tool crashes with wxWidget stacktrace

### ISSUE THREAD

**Issue by darkn3rd** [caskroom/homebrew-cask#13935] opened 2015-09-22 22:47 UTC
**SUMMARY**: Installing diffmege with cask yields crashing program when typing `diffmerge` from the command line.

**ACTUAL RESULTS**: Install diffmerge (`brew cask install diffmerge`) and type `diffmerge` from the console:

```bash
$ diffmerge
/build/sgdm400/Apple/intel/Release_patched/wxWidgets-3.0.0-rc1/src/common/arrstr.cpp(368): assert "nIndex < m_nCount" failed in RemoveAt(): bad index in wxArrayString::Remove
```
In the graphical application, a dialog titled **wxWidgets Debug Alert** pops up and states:

```
/build/sgdm400/Apple/intel/Release_patched/wxWidgets-3.0.0-rc1/src/common/arrstr.cpp(368): assert "nIndex < m_nCount" failed in RemoveAt(): bad index in wxArrayString::Remove

Call stack:
[00] wxFileName::RemoveLastDir()             
[01] dlg_paid::~dlg_paid()                   
[02] dlg_paid::~dlg_paid()                   
[03] wxURI::~wxURI()                         
[04] wxHashTable::~wxHashTable()             
[05] dlg_paid::~dlg_paid()                   
[06] wxLogger::DoLogTrace(wxString const&, wchar_t const*, ...) 
[07] 0x00000001              
```

**EXPECTED RESULTS**: Well, no crash.  After uninstalling with cask, and installing from the package, `DiffMerge.4.2.0.697.intel.stable.pkg`, I do not have the same user experience.  Typing `diffmerge` from the command line doesn't crash.

**Comment by jawshooah** [comment] 2015-09-24 15:41
Closing as duplicate of #11056.

**Closed by jawshooah** 2015-09-24 15:41 UTC
Labels: duplicate

**Comment by darkn3rd** [comment] 2015-09-27 08:12
Note.  My issue is a bug on a crash that is introduced by an installation by cask that would not normally occur in the originally product's installer.  You closed this issue as a duplicate of an enhancement request.

**Comment by jawshooah** [comment] 2015-09-27 15:29
That's a fair point. I believe the label for that issue has been changed accordingly.

Have you tried just clicking "Cancel" when that error dialog shows up? I've been coping with this error for months, and it has never had any actual impact on the performance of the app.

**Comment by darkn3rd** [comment] 2015-10-09 02:10
The app runs, except when called from the command line and used with tools like git diff.   As apart of our engineering process where I work, they use diffmerge with git.  I cannot recommend installing that particular tool with cask (other tools I've tried work fine, and Java is working better now).

```bash
curl -O http://download-us.sourcegear.com/DiffMerge/4.2.0/DiffMerge.4.2.0.697.intel.stable.pkg
sudo installer -pkg ~/Downloads/DiffMerge.4.2.0.697.intel.stable.pkg -target /
```
