### ISSUE TITLE
Removing `real-vnc` removes `/etc` symlink, which breaks the OS

### ISSUE THREAD

**Issue by maddie** [caskroom/homebrew-cask#33006] opened 2017-04-26 14:35 UTC
#### Description of issue

After installing `real-vnc`, using command `brew cask uninstall real-vnc` to uninstall it, removes the `/etc` symlink (!!!!!!), then breaks the system.

#### Output of your command with `--verbose --debug`

**If you're going to try this, make sure you have root shell (e.g. `sudo su`) already opened before you do this. Otherwise it might break your system and requires you to go into Recovery from USB or even a re-install. You can fix this by running `ln -s /private/etc /etc` with `root`.**

```
==> Uninstalling Cask real-vnc
==> Uninstalling Cask real-vnc
==> Un-installing artifacts
==> Determining which artifacts are present in Cask real-vnc
==> 4 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007f887f21ff98>
#<Hbc::Artifact::PreflightBlock:0x007f887f21c488>
#<Hbc::Artifact::Pkg:0x007f887f21f1b0>
#<Hbc::Artifact::Zap:0x007f887f21fed0>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for real-vnc; your password may be necessary
==> Removing launchctl service com.realvnc.vncserver
==> Executing: ["/bin/launchctl", "list", "com.realvnc.vncserver"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.realvnc.vncserver"]
==> Removing launchctl service com.realvnc.vncserver.peruser
==> Executing: ["/bin/launchctl", "list", "com.realvnc.vncserver.peruser"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.realvnc.vncserver.peruser"]
==> Uninstalling packages:
==> Executing: ["/usr/sbin/pkgutil", "--pkgs=com.realvnc.vncserver.pkg"]
com.realvnc.vncserver.pkg
==> Executing: ["/usr/sbin/pkgutil", "--files", "com.realvnc.vncserver.pkg"]
==> Executing: ["/usr/sbin/pkgutil", "--pkg-info-plist", "com.realvnc.vncserver.pkg"]
==> Deleting pkg symlinks and special files
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "--"]
==> rm: /etc/vnc/get_primary_ip4: No such file or directory
==> Deleting pkg directories
==> Executing: ["/usr/bin/stat", "-f", "%Of", "--", "/Library/vnc/VNC Chat.app/Contents/Resources/de.lproj"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/chmod", "--", "777", "/Library/vnc/VNC Chat.app/Contents/Resources/de.lproj"]
==> sudo: unable to stat /etc/sudoers: No such file or directory
==> sudo: no valid sudoers sources found, quitting
==> sudo: unable to initialize policy plugin
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/chmod", "--", "755", "/Library/vnc/VNC Chat.app/Contents/Resources/de.lproj"]
==> sudo: unable to stat /etc/sudoers: No such file or directory
==> sudo: no valid sudoers sources found, quitting
==> sudo: unable to initialize policy plugin
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /bin/chmod -- 755 #<Pathname:/Library/vnc/VNC Chat.app/Contents/Resources/de.lproj>

==> Standard Output of failed command:


==> Standard Error of failed command:
sudo: unable to stat /etc/sudoers: No such file or directory
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin


==> Exit status of failed command:
#<Process::Status: pid 28466 exit 1>
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:65:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:104:in `ensure in with_full_permissions'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:105:in `with_full_permissions'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:32:in `block in uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:29:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:29:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:191:in `block (2 levels) in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `block in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:34:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:349:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:346:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:346:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:331:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.13-129-gc6c930174e
caskroom/homebrew-cask (git revision a45af; last commit 2017-04-25)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 9.8MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3644 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1105 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/knqyf263/homebrew-pet (0 casks)
/usr/local/Homebrew/Library/Taps/mpv-player/homebrew-mpv (0 casks)
/usr/local/Homebrew/Library/Taps/neovim/homebrew-neovim (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
LC_CTYPE="UTF-8"
PATH="~/bin:~/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:~/Library/Android/sdk/platform-tools:/usr/local/opt/go/libexec/bin:~/.go/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

**Comment by commitay** [comment] 2017-04-26 21:36
I cannot reproduce this. 

`real-vnc` uninstall is currently broken https://github.com/caskroom/homebrew-cask/issues/32300 but your install seems to predate the addition of the`uninstall_preflight` so it is not affected by that issue. 

Changing my uninstall to match yours does not remove the `/etc` symlink.

**Comment by miccal** [comment] 2017-04-27 02:31
I also cannot reproduce this.

Ping @reitermarkus.

**Comment by maddie** [comment] 2017-04-27 02:33
Somehow I can reliably reproduce this :(

Now I'll just leave it there for the moment.

**Comment by reitermarkus** [comment] 2017-05-08 18:22
Closing this. I cannot reproduce this either.

**Closed by reitermarkus** 2017-05-08 18:22 UTC
Labels: awaiting maintainer feedback

**Comment by wjr1985** [comment] 2017-06-26 18:02
It's worth noting that I just ran into this now when removing `real-vnc`. I'm hesitant to re-run this for obvious reasons, but if there's any sort of logging or anything I could provide that could help with troubleshooting this after the fact let me know.
