### ISSUE TITLE
calibre install errors: version outdated

### ISSUE THREAD

**Issue by lolgear** [caskroom/homebrew-cask#13270] opened 2015-08-14 15:14 UTC
Hi! I have an issue with calibre install:
```
$ brew cask install --verbose calibre
==> Downloading https://github.com/kovidgoyal/calibre/releases/download/v2.34.0/calibre-2.34.0.dmg
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-481) https://github.com/kovidgoyal/calibre/releases/download/v2.34.0/calibre-2.34.0.dmg -C 0 -o /Library/Caches/Homebrew/calibre-2.34.0.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'calibre' with message: Download failed: https://github.com/kovidgoyal/calibre/releases/download/v2.34.0/calibre-2.34.0.dmg
```

also

```
$ brew upgrade brew-cask
Error: caskroom/cask/brew-cask 0.56.0 already installed
```

**Comment by scribblemaniac** [comment] 2015-08-14 15:19
Thank you for making a new issue. It appears that it needs to be upgraded to 2.35.0. Do you want to try doing this? It's not a very difficult change and we're here to help if necessary.

**Comment by lolgear** [comment] 2015-08-14 15:20
@scribblemaniac, yes, let's try, could you give instructions

**Comment by scribblemaniac** [comment] 2015-08-14 15:29
Start by checking out [CONTRIBUTING.md](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md). Instead of adding a new cask though, you will have to find the calibre cask and edit the version and sha256 lines.

**Comment by lolgear** [comment] 2015-08-14 15:34
@scribblemaniac, well, I don't have calibre version installed. How could I get file and get sha_sum from it?

**Comment by scribblemaniac** [comment] 2015-08-14 15:38
You can download the latest version of calibre from [https://github.com/kovidgoyal/calibre/releases/download/v2.35.0/calibre-2.35.0.dmg](https://github.com/kovidgoyal/calibre/releases/download/v2.35.0/calibre-2.35.0.dmg) and in terminal run `shasum -a 256 <path_to_downloaded_file>`. Of course you fill in the downloaded file path. You don't need to install calibre to do this, only download the dmg.

**Comment by lolgear** [comment] 2015-08-14 15:41
@scribblemaniac, please, tell me rules or style for commit message. 
"calibre: version updated to 2.35.0" will be enough?

**Comment by scribblemaniac** [comment] 2015-08-14 15:45
As long as you put the new version and the cask somewhere, it's a matter of personal preference. I personally prefer `calibre.rb: Upgrade to v2.35.0`, but many contributors have many different ways of doing it.

**Comment by lolgear** [comment] 2015-08-14 15:54
@scribblemaniac, should I make pull request to special branch as 'brew-cask-outdated'?

**Comment by scribblemaniac** [comment] 2015-08-14 16:06
Nope, just straight into master is fine.

**Comment by lolgear** [comment] 2015-08-14 16:08
https://github.com/caskroom/homebrew-cask/pull/13271

**Comment by Ngrd** [comment] 2015-08-14 16:55
Fixed in https://github.com/caskroom/homebrew-cask/pull/13265. Feel free to reopen this issue if the problem persists.

**Closed by Ngrd** 2015-08-14 16:55 UTC

**Comment by 1zaman** [comment] 2015-08-14 18:11
See #10039

**Comment by scribblemaniac** [comment] 2015-08-14 18:14
@1zaman This issue has been fixed and is closed. The issue you pointed to is also closed and is not relevant here.

**Comment by 1zaman** [comment] 2015-08-14 18:59
@scribblemaniac: The issue is _temporarily_ fixed, but it will occur again the next week. The issue I referenced is closed, but definitely relevant.

**Comment by vitorgalvao** [comment] 2015-08-14 21:11
> should I make pull request to special branch as 'brew-cask-outdated'?

Yes, @lolgear, you should always make changes into a new branch. Doing it directly on master many times has bad results.
