### ISSUE TITLE
Amethyst refuses to uninstall

### ISSUE THREAD

**Issue by bronson** [caskroom/homebrew-cask#23420] opened 2016-08-03 23:24 UTC
#### Description of issue

The amethyst cask refuses to uninstall on my computer.

<summary>Output of `brew cask uninstall --force --verbose`</summary>

```
==> Disabling accessibility access
==> Print: Entry, "CFBundleIdentifier", Does Not Exist
Error: amethyst: 'bundle_identifier' failed with: Command failed to execute!

==> Failed command:
["/usr/libexec/PlistBuddy", "-c", "Print CFBundleIdentifier", "#<Pathname:/Applications/Amethyst.app/Contents/Info.plist>"]

==> Standard Output of failed command:
File Doesn't Exist, Will Create: /Applications/Amethyst.app/Contents/Info.plist


==> Standard Error of failed command:
Print: Entry, "CFBundleIdentifier", Does Not Exist


==> Exit status of failed command:
#<Process::Status: pid 85276 exit 1>
Error: Kernel.exit
```

<details><summary>Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libwkhtmltox.0.12.2.dylib

Warning: Your Xcode (7.3) is outdated
Please update to Xcode 7.3.1.
Xcode can be updated from the App Store.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.11
==> macOS Release with Patchlevel:
10.11.6
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision b77a69; last commit 2016-08-02)
Homebrew/homebrew-core (git revision b400; last commit 2016-08-03)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-cask Version:
0.60.0 (git revision c72c9; last commit 34 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/usr/local/Caskroom
==> Homebrew-cask Cached Downloads:
/Users/bronson/Library/Caches/Homebrew/Cask
1 files, 76.3M (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
3272
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="node_modules/.bin:/Users/bronson/node_modules/.bin:/Users/bronson/.nvm/versions/io.js/v2.0.2/bin:/usr/local/bin:/usr/local/sbin:/Users/bronson/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/mysql/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
```
</details>

**Comment by bronson** [comment] 2016-08-03 23:26
Might be related to moving my casks to `/usr/local` as described in https://github.com/caskroom/homebrew-cask/issues/21913

**Comment by reitermarkus** [comment] 2016-08-04 01:16
No, this has nothing to do with moving it to `/usr/local`.

The order of the uninstall is causing this bug. `/Applications/Amethyst.app` is removed in the first step, but `/Applications/Amethyst.app/Contents/Info.plist` is needed to disable accessibility access.

**Comment by bronson** [comment] 2016-08-04 01:20
That makes sense.  Looks like the Spectacle cask is doing the same thing.  Should I open an issue for that one too?

**Comment by reitermarkus** [comment] 2016-08-04 01:32
No, this happens with every cask that uses `accessibility_access true`.

Could you try reinstalling (without `--force`) and then uninstalling (also without `--force`) again?

**Comment by bronson** [comment] 2016-08-04 03:51
Seems to work fine:

```
~$ brew cask install amethyst
==> Downloading https://ianyh.com/amethyst/versions/Amethyst-0.10.1.zip
######################################################################## 100.0%
==> Verifying checksum for Cask amethyst
==> Moving App 'Amethyst.app' to '/Applications/Amethyst.app'
==> Enabling accessibility access
Password:
🍺  amethyst was successfully installed!
~$ brew cask uninstall amethyst
==> Disabling accessibility access
==> Removing App: '/Applications/Amethyst.app'
==> Running uninstall process for amethyst; your password may be necessary
==> Removing login item Amethyst
~$ ls /usr/local/Caskroom/amethyst/
0.9.4
```

Of course, the old version remains...  should I just rm -rf it?

**Comment by vitorgalvao** [comment] 2016-08-04 15:54
> Of course, the old version remains... should I just rm -rf it?

Yes.

**Closed by vitorgalvao** 2016-08-04 15:54 UTC
Labels: bug, cask

**Comment by bronson** [comment] 2016-08-04 17:47
@vitorgalvao this is still a bug, isn't it?

Or is the solution to just never run `brew update`?

**Comment by vitorgalvao** [comment] 2016-08-04 17:50
> this is still a bug, isn't it?

Yes. One we’re aware of, along with many others in the uninstallation process.

Or is the solution to just never run `brew update`?

`brew update` wasn’t the cause. It was the change/removal of the app bundle.

**Comment by bronson** [comment] 2016-08-04 17:57
Tracked elsewhere?  Gotcha, that makes sense.  Thanks!

avoiding `brew update` is just a super-crappy workaround.  :)
