### ISSUE TITLE
cask zap oascript error

### ISSUE THREAD

**Issue by monouser7dig** [caskroom/homebrew-cask#42182] opened 2017-12-21 14:44 UTC
probably [related to](https://github.com/caskroom/homebrew-cask/issues/41786#issuecomment-350528837)

(I had the same/ very similar issue on another formula some days back but did not report/ remember)

#### Description of issue

I ran `brew cask zap github-desktop`

#### Output of your command with `--verbose --debug`

```
==> Implied "brew cask uninstall github-desktop"
==> Moving App 'GitHub Desktop.app' back to '/usr/local/Caskroom/github-desktop/1.0.4
==> Unlinking Binary '/usr/local/bin/github'.
==> Dispatching zap stanza
==> Running zap process for github-desktop; your password may be necessary
==> Removing files:
~/Library/Application Support/ShipIt_stderr.log
Password:
~/Library/Application Support/ShipIt_stdout.log
~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.github.GitHubClient.sfl
~/Library/Caches/com.github.GitHubClient
~/Library/Caches/com.github.GitHubClient.ShipIt
==> Trashing files:
~/Library/Application Support/GitHub Desktop
~/Library/Application Support/com.github.GitHubClient
~/Library/Application Support/com.github.GitHubClient.ShipIt
~/Library/Preferences/com.github.GitHubClient.helper.plist
~/Library/Preferences/com.github.GitHubClient.plist
==> osascript: can't open default scripting component.
Error: Command failed to execute!

==> Failed command:
/usr/bin/osascript -e on run argv
  repeat with i from 1 to (count argv)
    set item i of argv to (item i of argv as POSIX file)
  end repeat

  tell application "Finder"
    set trashedItems to (move argv to trash)
    set output to ""

    repeat with i from 1 to (count trashedItems)
      set trashedItem to POSIX path of (item i of trashedItems as string)
      set output to output & trashedItem
      if i < count trashedItems then
        set output to output & character id 0
      end if
    end repeat

    return output
  end tell
end run
~/Library/Application Support/GitHub Desktop ~/Library/Preferences/com.github.GitHubClient.helper.plist ~/Library/Preferences/com.github.GitHubClient.plist

==> Standard Output of failed command:


==> Standard Error of failed command:
osascript: can't open default scripting component.


==> Exit status of failed command:
#<Process::Status: pid 75106 exit 1>
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.4.1-7-g75d0321
caskroom/homebrew-cask (git revision 72a2a; last commit 2017-12-21)
==> macOS
10.13.2
==> Java
9.0.1, 1.8.0_144
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 56.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3865 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (138 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1113 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by vitorgalvao** [comment] 2017-12-21 14:59
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Please follow the *whole* template and don’t delete it. If you prefer, you may close this issue and open a new one.

**Comment by monouser7dig** [comment] 2017-12-21 15:03
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

after running `brew cask zap github-desktop -f`
```
brew cask zap github-desktop -f
==> Implied "brew cask uninstall github-desktop"
Warning: It seems there is already an App at '/usr/local/Caskroom/github-desktop/1.0.4-6e5e9664/GitHub Desktop.app'; overwriting.
==> Removing App '/usr/local/Caskroom/github-desktop/1.0.4-6e5e9664/GitHub Desktop.ap
Error: It seems the App source '/Applications/GitHub Desktop.app' is not there.
```

**Comment by vitorgalvao** [comment] 2017-12-21 16:12
I couldn’t reproduce the error. Since it seems to be fixed for you, I’ll close and keep an eye open for similar reports. Thank you.

**Comment by monouser7dig** [comment] 2017-12-21 16:32
It happens for sourcetree as well as another example

**Comment by vitorgalvao** [comment] 2017-12-21 19:39
Cannot reproduce. If no one else reports the same in a few days, we’ll chalk it up to a weirdness on your setup.

**Comment by commitay** [comment] 2017-12-21 19:52
@monouser7dig What happens if you run `/usr/bin/osascript -e 'tell app "Finder" to display dialog "This is a test!"'`?

**Comment by monouser7dig** [comment] 2017-12-21 22:58
it did not work, I reinstalled HighSierra and it worked again (found this online) and now the zap works as well

wonky high sierra again

**Closed** 2017-12-21 23:10 UTC
