### ISSUE TITLE
refactor CLI argument processing

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#5000] opened 2014-06-19 23:31 UTC
- [ ] argument processing is spread between multiple files, and should be consolidated
- [ ] methods corresponding to CLI flags are defined on the `Cask` namespace, and should probably be isolated into `Cask::Opt` namespace
- [ ] global flags should be differentiated from flags to subcommands
- [ ] subcommands should have a common interface for defining which flags they will accept
- [ ] the global `ARGV` should be processed only once, and thereafter not consulted directly
- [ ] all arguments should be processed to completion.  Currently, unknown or misspelled flags such as `--verrbose` typically go unprocessed and are silently ignored. **BUG**
- [ ] much of the desired functionality may be available in a library, but (to be useful) the library must work across Ruby 1.8 - 2.0, and must also support the subcommand model

**Comment by TechZen** [comment] 2015-02-05 17:58
Misspelled commands still an issue. 

![brew cask install bug](https://cloud.githubusercontent.com/assets/2874035/6065843/048d9418-ad2e-11e4-8388-e39be71f53f3.png)

**Comment by vitorgalvao** [comment] 2015-02-05 18:21
@TechZen None of the points in the issue is marked as done and the issue is still open; it’s natural the problems still exists. Still, your example doesn’t apply at all — misspelling `install` as `instal` works withou a problem, the issue in your case is a cask toke misspelling.

**Comment by reitermarkus** [comment] 2017-05-23 15:12
Done in https://github.com/Homebrew/brew/pull/2654.

**Closed by reitermarkus** 2017-05-23 15:12 UTC
Labels: core, enhancement
