### ISSUE TITLE
Cask upgrade fail on VLC because "older version is already here"

### ISSUE THREAD

**Issue by Porkepix** [caskroom/homebrew-cask#45942] opened 2018-04-14 10:18 UTC
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

VLC didn't upgraded to latest version with normal use case. **It did works with `--force`** but it looks abnormal it failed without, which is why I thought it was still worth an issue.

#### Command that failed

```
brew cask upgrade vlc
```

#### Output of command with `--force --verbose --debug`

Output without `--force` **on purpose**: It worked with `--force` but it seems abnormal considering output and current situation for the upgrade to fail without a `--force` and succeed with it. Another cask upgraded successfully just before.
```
mbp :: ~ » brew cask upgrade --verbose vlc                                                                                               1 ↵
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
vlc 3.0.1
==> Satisfying dependencies
==> Downloading https://get.videolan.org/vlc/3.0.1/macosx/vlc-3.0.1.dmg
Already downloaded: /Users/clement/Library/Caches/Homebrew/Cask/vlc--3.0.1.dmg
==> Verifying checksum for Cask vlc
==> Starting upgrade for Cask vlc
==> Purging files for version 3.0.1 of Cask vlc
Error: It seems there is already an App at '/usr/local/Caskroom/vlc/2.2.4/VLC.app'.
Error: Kernel.exit
```

It seems to complain about 2.2.4 already in place… to install 3.0.1.

#### Output of `brew cask doctor`

```
mbp :: ~ » brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.6.0-15-g5005999
caskroom/homebrew-cask (git revision faf76; last commit 2018-04-14)
==> macOS
10.9.4
==> SIP
N/A
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 44.7MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3961 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
mbp :: ~ » brew tap
Updating Homebrew...
caskroom/cask
denschub/dino
homebrew/core
homebrew/dupes
```

**Comment by commitay** [comment] 2018-04-14 10:26
> It seems to complain about 2.2.4 already in place… to install 3.0.1.

It's complaining because it can't back up the existing install to `/usr/local/Caskroom/vlc/2.2.4/`

Do you have the out from running it with `--force`?

**Comment by Porkepix** [comment] 2018-04-14 10:29
Yup, still having it:

```
mbp :: ~ » brew cask upgrade --verbose --force vlc                                                                                       
==> Upgrading 1 outdated package, with result:
vlc 3.0.1
==> Satisfying dependencies
==> Downloading https://get.videolan.org/vlc/3.0.1/macosx/vlc-3.0.1.dmg
Already downloaded: /Users/clement/Library/Caches/Homebrew/Cask/vlc--3.0.1.dmg
==> Verifying checksum for Cask vlc
==> Starting upgrade for Cask vlc
Warning: It seems there is already an App at '/usr/local/Caskroom/vlc/2.2.4/VLC.app'; overwriting.
==> Removing App '/usr/local/Caskroom/vlc/2.2.4/VLC.app'.
==> Backing App 'VLC.app' up to '/usr/local/Caskroom/vlc/2.2.4/VLC.app'.
==> Removing App '/Applications/VLC.app'.
==> Unlinking Binary '/usr/local/bin/vlc'.
==> Moving App 'VLC.app' to '/Applications/VLC.app'.
==> Linking Binary 'vlc.wrapper.sh' to '/usr/local/bin/vlc'.
==> Purging files for version 2.2.4 of Cask vlc
🍺  vlc was successfully upgraded!
```

**Comment by commitay** [comment] 2018-04-14 10:39
`==> Removing App '/usr/local/Caskroom/vlc/2.2.4/VLC.app'.`

It's working as intended (warn by default and overwrite with `--force`)  but it is strange there already was a copy of the app in `Caskroom/vlc/2.2.4`

Closing as there isn't anything for us to fix but thanks for reporting this nonetheless!

**Closed by commitay** 2018-04-14 10:39 UTC
