### ISSUE TITLE
Google Chrome Fails to Open (sierra)

### ISSUE THREAD

**Issue by todd-dsm** [caskroom/homebrew-cask#29902] opened 2017-02-06 22:04 UTC
Hey guys, new version of homebrew installed just yesterday. Installed the Google Chrome cask then it failed, due to a permissions error when I tried to open it.

To get past the issue I had to first:
```bash
mkdir -p "$HOME/Library/Application\ Support/Google/Chrome"
chown -R "$USER:$(id -gn)" "$HOME/Library/Application Support"/
```

Then run the install. 

Other, hopefully useful, details; formula:
```bash
brew cask info google-chrome
google-chrome: latest
https://www.google.com/chrome/
/usr/local/Caskroom/google-chrome/latest (57K)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/google-chrome.rb
==> Name
Google Chrome
==> Artifacts
Google Chrome.app (app)
```

The install details:
```bash
brew cask list google-chrome
==> Apps
/Applications/Google Chrome.app (193 files, 167.3M)
```

I found the audit command; not sure of it's value.
```bash
brew cask audit | grep -i chrome
audit for chrome-devtools: passed
audit for chrome-remote-desktop-host: passed
audit for dmm-player-for-chrome: passed
audit for epichrome: passed
audit for google-chrome: passed
audit for mkchromecast: passed
audit for google-chrome-beta: passed
audit for google-chrome-canary: passed
audit for google-chrome-dev: passed
```

**Comment by miccal** [comment] 2017-02-06 23:17
I cannot reproduce this:
```
-bash-4.4.12- /Users/miccal [> brew cask install google-chrome
==> Satisfying dependencies
complete
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
######################################################################## 100.0%
==> No checksum defined for Cask google-chrome, skipping verification
==> Moving App 'Google Chrome.app' to '/Applications/Google Chrome.app'
🍺  google-chrome was successfully installed!
```

**Comment by miccal** [comment] 2017-02-06 23:25
@todd-dsm can you post the output of your `brew doctor`, `brew cask doctor` and `brew config` please.

**Comment by todd-dsm** [comment] 2017-02-06 23:35
@miccal It will install just fine but it will error when you open Chrome in the GUI. 
Maybe you have to remove the directory after uninstalling it:
`rm -rf "$HOME/Library/Application\ Support/Google/Chrome"`. 

That directory doesn't exist on a new install.

The details you requested:
```bash
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.6m/greenlet/greenlet.h
```

```bash
brew cask doctor
==> macOS Release:
10.12.3
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.9
Homebrew/homebrew-core (git revision f205; last commit 2017-02-04)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.9
caskroom/homebrew-cask (git revision a636cf; last commit 2017-02-05)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/thomas/Library/Caches/Homebrew/Cask
13 files, 1.3G (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions
==> Homebrew-Cask Default Tap Cask Count:
3530
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/local/opt/tcl-tk/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
```


```bash
brew config
HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 664d0c67d5947605c914c4c56ebcfaa80cb6eca0
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f205a58d52cb3a1786ab6d713b3c613018454b57
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_121
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

**Comment by miccal** [comment] 2017-02-06 23:50
> @miccal It will install just fine but it will error when you open Chrome in the GUI.

What was the error exactly?

**Comment by todd-dsm** [comment] 2017-02-06 23:56
It was a GUI error. Of course, I was in a hurry and worked through it without saving a lot of detail.

I won't be able to get that for you till later, possibly tomorrow.

**Comment by miccal** [comment] 2017-02-07 00:28
I just tested again on a different machine with `install` then `ununstall` (so the folder `~/Library/Application Support/Google/Chrome` remained) and `install` again, and had no issues.

On a side note, I have [Little Flocker](https://github.com/caskroom/homebrew-cask/blob/master/Casks/little-flocker.rb) and [Little Snitch](https://github.com/caskroom/homebrew-cask/blob/master/Casks/little-snitch.rb) installed on my machine, and they both went _crazy_ when I opened `Google Chrome.app` - this program reads _a lot_ of files and connects to _a lot_ of websites when starting!

**Comment by vitorgalvao** [comment] 2017-02-07 00:34
The only thing we do in Chrome’s case is download the it and move it to it’s correct place. Whatever error you encountered was not related to HBC, as demonstrated by @miccal not being able to reproduce and this error never having happened to anyone else. Closing.

Though you should still feel free to reply if you and @miccal are interested in finding the cause. But it’s unlikely to have anything to do with HBC, so no point in keeping the issue open.

**Closed by vitorgalvao** 2017-02-07 00:34 UTC
Labels: awaiting user reply
