### ISSUE TITLE
Bug report: `brew cask audit` outputs Error: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by rgoldberg** [caskroom/homebrew-cask#23472] opened 2016-08-05 17:03 UTC
#### Description of issue

Ran `brew cask audit`

<details><summary>Output of `brew cask audit --verbose`</summary>

```
audit for 010-editor: passed
audit for 0ad: passed
audit for 0xed: passed
audit for 115browser: passed
audit for 1clipboard: passed
audit for 1password: passed
audit for 33-rpm: passed
audit for 4k-stogram: passed
audit for 4k-video-downloader: passed
audit for 4k-youtube-to-mp3: passed
audit for 4peaks: passed
audit for 5iler: passed
audit for 5kplayer: passed
audit for 8tracksradiohelper: passed
audit for a-better-finder-attributes: passed
audit for a-better-finder-rename: passed
audit for a-slower-speed-of-light: passed
audit for abgx360: passed
audit for ableton-live: passed
audit for abricotine: passed
audit for abscissa: passed
audit for abyss: passed
audit for accessmenubarapps: passed
audit for acorn: passed
audit for acquia-dev-desktop: passed
audit for across-lite: passed
audit for acslogo: passed
audit for actions-server: passed
audit for activity-audit: passed
audit for actotracker: passed
audit for actprinter: passed
audit for actual-odbc-pack: passed
audit for adafruit-arduino: passed
audit for adapter: passed
audit for adguard: passed
audit for adium: passed
audit for adobe-acrobat: passed
audit for adobe-air: passed
audit for adobe-animate-cc: passed
audit for adobe-arh: passed
audit for adobe-bloodhound: passed
audit for adobe-bridge-cc: passed
audit for adobe-creative-cloud-cleaner-tool: passed
audit for adobe-creative-cloud: passed
audit for adobe-digital-editions: passed
audit for adobe-dng-converter: passed
audit for adobe-illustrator-cc: passed
audit for adobe-indesign-cc: passed
audit for adobe-photoshop-cc: passed
audit for adobe-photoshop-lightroom: passed
audit for adobe-reader: passed
audit for adpassmon: passed
audit for adventure: passed
audit for adware-removal-tool: passed
audit for aegisub: passed
audit for aerial: passed
audit for aether: passed
audit for affinic-debugger-gui: passed
audit for after-dark-classic: passed
audit for aimersoft-video-converter-ultimate: passed
audit for air-connect: passed
audit for air-video-server-hd: passed
audit for airdisplay: passed
audit for airdroid: passed
audit for airfile: passed
audit for airflick: passed
audit for airflow: passed
audit for airfoil: passed
audit for airmedia: passed
audit for airparrot: passed
audit for airserver: passed
audit for airstream: passed
audit for airtame: passed
audit for airtool: passed
audit for airvpn: passed
audit for airy: passed
audit for aja-system-test: passed
audit for aladin: passed
audit for alarm-clock: passed
audit for alcatraz: passed
audit for alchemy: passed
audit for alfred: passed
audit for algodoo: passed
audit for alib1: passed
audit for alice: passed
audit for aliedit: passed
audit for alinof-timer: passed
audit for aliwangwang: passed
audit for aliworkbench: passed
audit for alternote: passed
audit for amadeus-pro: passed
audit for amazon-drive: passed
audit for amazon-music: passed
audit for amazon-workdocs: passed
audit for amazon-workspaces: passed
audit for amethyst: passed
audit for amidst: passed
audit for ammonite: passed
audit for ampps: passed
audit for anaconda: passed
audit for anatine: passed
audit for android-file-transfer: passed
audit for android-studio: passed
audit for androidtool: passed
audit for andy: passed
audit for angband: passed
audit for angry-ip-scanner: passed
audit for animated-gif-quicklook: passed
audit for anki: passed
audit for anonvpn: passed
audit for anonym: passed
audit for antconc: passed
audit for antetype: passed
audit for antfileconverter: passed
audit for antpconc: passed
audit for antwordprofiler: passed
audit for anvil: passed
audit for anybar: passed
audit for anyipsum: passed
audit for anylist: passed
audit for anylogic: passed
audit for anypass: passed
audit for anytrans: passed
audit for apache-couchdb: passed
audit for apache-directory-studio: passed
audit for apm-planner: passed
audit for apogee-duet: passed
audit for app-tamer: passed
audit for appcleaner: passed
audit for appcode: passed
audit for appdelete: passed
audit for appearin: passed
audit for appfresh: passed
audit for appium: passed
audit for applepi-baker: passed
audit for application-loader: passed
audit for apppolice: passed
audit for appserver: passed
audit for appstore-quickview: passed
audit for apptivate: passed
audit for apptrans: passed
audit for apptrap: passed
audit for appzapper: passed
audit for aptanastudio: passed
audit for aqua-data-studio: passed
audit for aquamacs: passed
audit for aquaskk: passed
audit for aquaterm: passed
audit for araxis-merge: passed
audit for archi: passed
audit for archiver: passed
audit for arduino: passed
audit for argouml: passed
audit for aria-maestosa: passed
audit for armitage: passed
audit for armory: passed
audit for arq: passed
audit for arranger: passed
audit for arrsync: passed
audit for art-directors-toolkit: passed
audit for art-of-illusion: passed
audit for ascension: passed
audit for aseprite: passed
audit for asepsis: passed
audit for astah-community: passed
audit for astah-professional: passed
audit for astah-sysml: passed
audit for astrill: passed
audit for astropad: passed
audit for atext: passed
audit for atlantis: passed
audit for atlauncher: passed
audit for atom: passed
audit for atraci: passed
audit for au-lab: passed
audit for audacity-lame-library: passed
Error: undefined method `[]' for nil:NilClass
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:44:in `block (3 levels) in load_cask'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:153:in `open_uri'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:42:in `block (2 levels) in load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/url.rb:13:in `call'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/url.rb:13:in `block in from'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/dsl/stanza_proxy.rb:6:in `block in once'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/dsl/stanza_proxy.rb:19:in `call'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/dsl/stanza_proxy.rb:19:in `to_s'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/audit.rb:150:in `bad_url_format?'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/audit.rb:155:in `bad_sourceforge_url?'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/audit.rb:142:in `check_download_url_format'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/audit.rb:137:in `check_url'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/audit.rb:21:in `run!'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/auditor.rb:5:in `audit'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:29:in `audit'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:22:in `block in run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:21:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:21:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:7:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:108:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:146:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:23:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:22:in `require?'
/usr/local/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libecomlodr.dylib
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.11
==> macOS Release with Patchlevel:
10.11.6
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 66d56; last commit 2016-08-05)
Homebrew/homebrew-core (git revision 7a1c; last commit 2016-08-05)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-cask Version:
0.60.0 (git revision dbbc; last commit 89 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/usr/local/Caskroom
==> Homebrew-cask Cached Downloads:
/Users/ross.goldberg/Library/Caches/Homebrew/Cask
0 files, 0B
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
3267
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Gems/2.0.0/gems/psych-2.1.0/lib
/Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/psych-2.1.0
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/ross.goldberg/.sdkman/candidates/gradle/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
```
</details>

**Comment by jawshooah** [comment] 2016-08-05 17:13
Duplicate of https://github.com/caskroom/homebrew-cask/issues/23463. Please search for your issue before creating a new one.

**Closed by jawshooah** 2016-08-05 17:13 UTC
