### ISSUE TITLE
java version "1.8.0_66" in brew cask

### ISSUE THREAD

**Issue by rchlin** [caskroom/homebrew-cask#14645] opened 2015-10-25 13:01 UTC
After I run **brew cask install java** to install the 1.8.0_66 version, I found that **Java update** in **Java control panel** didn't work.
Is there a bug about this java version or brew cask of installing java?

**Comment by vitorgalvao** [comment] 2015-10-25 17:42
Cannot reproduce on a clean Yosemite VM. Either this is an issue with your OS X version (if it is different) or with your specific setup.

The way to confirm it is uninstalling and reinstalling manually. Are you able to do that?

**Comment by adityadalal924** [comment] 2015-10-25 17:47
The cask basically only runs the pkg installer from [here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) with a few changes to prevent java apps from crashing. Should not have any effect on manually updating (and cannot reproduce on OSX 10.11)

**Comment by rchlin** [comment] 2015-10-26 10:42
@vitorgalvao @adityadalal924 thanks. I have uninstalled and reinstalled it manually, and **Java update** still didn't work. So I think it may be the problem of the **1.8.0_66 version jdk** or my OS X. By the way, my OS X version is 10.10.5, and I found that **brew cask cleanup** left an empty directory of name **jdk1.8.0_66.jdk** in **/Library/Java/JavaVirtualMachines/**.

**Comment by vitorgalvao** [comment] 2015-10-26 13:29
> So I think it may be the problem of the 1.8.0_66 version jdk or my OS X

Since neither I nor @adityadalal924 can reproduce (and I’m testing on a clean VM as the same OS X version as yourself), it seems like the problem is in your setup. Let’s wait a bit and see if any other maintainer has an insight. If none has, we’ll have to close this.

**Comment by adityadalal924** [comment] 2015-10-26 14:24
The only thing I can think of is if you removed the Java Updater manually (with `Lingon X` or similar)

------------------------------

To get a clean install:

```
sudo rm -fr /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin 
sudo rm -fr /Library/PreferencePanes/JavaControlPanel.prefpane
```
and delete old versions from `/Library/Java/JavaVirtualMachines`

(running `/usr/libexec/java_home -verbose` should show nothing at this point)

and you can finish with `brew uninstall java && brew install java` if so desired

**Comment by adityadalal924** [comment] 2015-11-06 14:30
Doesn't look like there's any other feedback on the issue - closing it as it cannot be reproduced and it's been > 10 days.

**Closed by adityadalal924** 2015-11-06 14:30 UTC
Labels: awaiting maintainer feedback
