### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by banj** [caskroom/homebrew-cask#8578] opened 2015-01-01 21:06 UTC
Ran `brew install Caskroom/cask/java`
which downloaded the binary and then timed out; re-ran the process and got back:
```
==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u25-b17/jdk-8u25-macosx-x64.dmg
Already downloaded: /Library/Caches/Homebrew/java-1.8.0_25.dmg
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/download.rb:41:in `block in _check_sums'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/download.rb:39:in `each'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/download.rb:39:in `_check_sums'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/download.rb:32:in `perform'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/installer.rb:72:in `download'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/installer.rb:49:in `install'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.43.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:59:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

**Comment by rolandwalker** [comment] 2015-01-01 21:23
Hi!

This is a duplicate of #7946.

A fix has been in release since [v0.50.0](https://github.com/caskroom/homebrew-cask/releases/tag/v0.50.0).  The following command should fix the issue:
```bash
$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Closed by rolandwalker** 2015-01-01 21:23 UTC
Labels: duplicate
