### ISSUE TITLE
 Different Eclipse bundles silently overriding one symlink

### ISSUE THREAD

**Issue by NickVolynkin** [caskroom/homebrew-cask#11454] opened 2015-05-30 10:27 UTC
This is more of a feature request than a bug report.

I've installed two eclipse recipes consecutively:
- eclipse-platform
- eclipse-cpp

First was symlinked to `Users/username/Applications/Eclipse.app`, the latter had overriden the same symlink. I was expecting Homebrew at least to notice that it overrides own symlink.

Now the only way to recover symlink  to `eclipse-platform` *with Homebrew* is to `brew cask uninstall` and `brew cask install` again. This will remove all settings and plugins, hence not an option.

( Yes, I can do it all manually, but isn't it what a package manager is made for?)

What behaviour would be better:
- In all Eclipse recipes and other similar groups change symlink names to unique.
- An argument to change default name for symlink
- A prompt to rename or override an existing symlink
- A command to repair setup for installed package

**Comment by vitorgalvao** [comment] 2015-05-30 15:27
Duplicate of https://github.com/caskroom/homebrew-cask/issues/8841.

There’s a [suggestion](https://github.com/caskroom/homebrew-cask/issues/8841#issuecomment-69617990) there to fix this. You can follow through with it, if you so wish.

**Closed** 2015-05-30 15:28 UTC

**Comment by NickVolynkin** [comment] 2015-05-30 15:52
Thank you, I couldn't find that ticket.
